(()=>{
const C=window.NEXUS_CONFIG||{};if(!C.supabaseUrl||!C.supabaseAnonKey||!window.supabase)return;const sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function can(p){const{data}=await sb.rpc('has_permission',{p_permission_code:p});return data===true}
function activate(id,label){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.submenu button').forEach(x=>x.classList.remove('active'));const c=document.getElementById('breadcrumb');if(c)c.textContent='NEXUS / '+label}
function nav(){const n=document.getElementById('nav');if(!n||document.getElementById('nxnav-arap'))return;let s=[...n.querySelectorAll('.nav-section')].find(x=>x.querySelector('.nav-main')?.textContent?.includes('Keuangan'));if(!s)return;const b=document.createElement('button');b.id='nxnav-arap';b.textContent='AR / AP';b.onclick=()=>{activate('nx-arap','AR / AP');render()};s.querySelector('.submenu').appendChild(b)}
function p(){let x=document.getElementById('nx-arap');if(!x){x=document.createElement('section');x.className='page';x.id='nx-arap';document.getElementById('pages')?.appendChild(x)}return x}
const t=(rows,cols)=>rows?.length?`<div class="table"><table><thead><tr>${cols.map(x=>`<th>${x[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(x=>`<td>${esc(r[x[0]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="empty">Belum ada data.</div>`;
async function render(){const x=p();x.innerHTML='<div class="hero"><div><div class="eyebrow">FINANCE / AR AP</div><div class="title">Piutang & Utang</div><div class="desc">Kontrol invoice customer, tagihan vendor/partner, aging, dan outstanding yang terhubung dengan pembukuan.</div></div><button class="secondary" id="nxArRefresh">↻ Refresh</button></div><div class="split"><div class="card"><h3>Accounts Receivable</h3><div id="ar"></div></div><div class="card"><h3>Accounts Payable</h3><div id="ap"></div></div></div><div class="card" style="margin-top:13px"><h3>Invoice / Bill Engine</h3><div class="notice">Invoice dan bill sudah memiliki struktur database. Pembuatan/posting dokumen akan mengikuti permission <b>accounting.manage</b> dan periode pembukuan.</div></div>';
x.querySelector('#nxArRefresh').onclick=render;const [{data:ar},{data:ap}]=await Promise.all([sb.from('accounts_receivable_summary').select('*'),sb.from('accounts_payable_summary').select('*')]);x.querySelector('#ar').innerHTML=t(ar,[['customer_id','Customer'],['open_invoices','Open'],['invoiced_amount','Invoiced'],['paid_amount','Paid'],['outstanding_amount','Outstanding']]);x.querySelector('#ap').innerHTML=t(ap,[['counterparty_id','Counterparty'],['open_bills','Open'],['billed_amount','Billed'],['paid_amount','Paid'],['outstanding_amount','Outstanding']]);}
async function boot(){if(!(await can('accounting.view')))return;nav();p();}
window.addEventListener('load',()=>setTimeout(boot,1000));
})();
