(() => {
  const CFG = window.NEXUS_CONFIG || {};
  if (!CFG.supabaseUrl || !CFG.supabaseAnonKey) return;
  const sb = supabase.createClient(CFG.supabaseUrl, CFG.supabaseAnonKey);
  const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label = s => String(s).replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
  const configs = {
    'fleet-types': {title:'Data Kendaraan',table:'vehicle_types',perm:'fleet.manage',key:'id',fields:[['name','text'],['slug','text'],['category','text'],['capacity','text'],['brand','text'],['model','text'],['year_from','number'],['year_to','number'],['sort_order','number'],['image_path','text'],['description','textarea'],['active','boolean']]},
    'fleet-units': {title:'Unit Kendaraan',table:'vehicle_units',perm:'fleet.manage',key:'id',fields:[['vehicle_type_id','uuid'],['source_type','text'],['unit_code','text'],['registration_number','text'],['manufacture_year','number'],['color','text'],['status','text'],['acquisition_date','date'],['notes','textarea']]},
    'crm-master': {title:'Customer Master',table:'customers',perm:'customer.manage',key:'id',fields:[['full_name','text'],['phone','text'],['email','email'],['company_name','text'],['customer_type','text'],['status','text'],['source_channel','text'],['notes','textarea']]},
    'crm-interaction': {title:'Interaksi Customer',table:'customer_interactions',perm:'customer.manage',key:'id',fields:[['customer_id','uuid'],['interaction_type','text'],['channel','text'],['subject','text'],['notes','textarea'],['occurred_at','datetime-local']]},
    'partner-master': {title:'Partner Master',table:'partners',perm:'partner.manage',key:'id',fields:[['partner_code','text'],['name','text'],['contact_person','text'],['phone','text'],['email','email'],['address','textarea'],['status','text'],['reliability_score','number'],['notes','textarea']]},
    'sales-campaign': {title:'Marketing Campaign',table:'marketing_campaigns',perm:'marketing.manage',key:'id',fields:[['campaign_code','text'],['name','text'],['objective','text'],['status','text'],['start_date','date'],['end_date','date'],['budget','number'],['currency_code','text'],['landing_path','text'],['utm_source','text'],['utm_medium','text'],['utm_campaign','text'],['notes','textarea']]},
    'sales-promo': {title:'Website Promo / Iklan',table:'website_campaigns',perm:'website.manage',key:'id',fields:[['campaign_type','text'],['title','text'],['subtitle','text'],['body','textarea'],['cta_label','text'],['cta_url','text'],['image_url','text'],['priority','number'],['start_at','datetime-local'],['end_at','datetime-local'],['active','boolean']]},
    'finance-expense': {title:'Pengeluaran',table:'expenses',perm:'accounting.manage',key:'id',fields:[['expense_code','text'],['expense_date','date'],['account_id','uuid'],['cost_center_id','uuid'],['description','text'],['amount','number'],['currency_code','text'],['status','text'],['vendor_name','text'],['notes','textarea']],noDelete:true},
    'hr-employee': {title:'Employee Master',table:'employees',perm:'hr.manage',key:'id',fields:[['employee_code','text'],['department_id','uuid'],['full_name','text'],['phone','text'],['email','email'],['job_title','text'],['employment_type','text'],['status','text'],['join_date','date'],['end_date','date'],['notes','textarea']]},
    'sales-source': {title:'Social / Source',table:'social_accounts',perm:'marketing.manage',key:'id',fields:[['platform','text'],['account_name','text'],['handle','text'],['profile_url','text'],['status','text'],['notes','textarea']]},
    'network-agent': {title:'Agent Master',table:'agents',perm:'customer.manage',key:'id',fields:[['agent_code','text'],['name','text'],['phone','text'],['email','email'],['status','text'],['commission_rate','number'],['notes','textarea']]}
  };
  let lastPage='';
  let currentCfg=null;
  function activePage(){ return document.querySelector('.page.active')?.id || document.querySelector('.submenu button.active')?.dataset?.page || ''; }
  async function can(code){ const {data}=await sb.rpc('has_permission',{p_permission_code:code}); return data===true; }
  function controlHost(){ return document.querySelector('.page.active'); }
  function ensureStyle(){ if(document.getElementById('nxCrudStyle')) return; const s=document.createElement('style'); s.id='nxCrudStyle'; s.textContent=`.nx-crud{margin-top:16px}.nx-crud .nx-head{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.nx-crud .nx-actions{display:flex;gap:7px;flex-wrap:wrap}.nx-crud table{width:100%;border-collapse:collapse}.nx-crud th,.nx-crud td{padding:9px 7px;border-bottom:1px solid #252a31;text-align:left;vertical-align:top}.nx-crud th{font-size:9px;color:#8e949f;text-transform:uppercase}.nx-crud td{font-size:11px}.nx-crud .nx-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.nx-crud .nx-form label{font-size:10px;color:#aeb3bc}.nx-crud .nx-form input,.nx-crud .nx-form textarea,.nx-crud .nx-form select{width:100%;margin-top:5px;background:#0b0e13;border:1px solid #363b45;color:#fff;border-radius:9px;padding:9px}.nx-crud .nx-form .full{grid-column:1/-1}.nx-modal{position:fixed;inset:0;background:#000b;display:none;align-items:center;justify-content:center;padding:18px;z-index:999}.nx-modal.open{display:flex}.nx-modal-card{width:min(760px,100%);max-height:90vh;overflow:auto;background:#101319;border:1px solid #272c35;border-radius:16px;padding:20px}.nx-muted{color:#8e949f;font-size:11px}@media(max-width:650px){.nx-crud .nx-form{grid-template-columns:1fr}}`; document.head.appendChild(s); }
  function inputFor(name,type,value){ const v=value ?? ''; if(type==='boolean') return `<input data-f="${name}" type="checkbox" ${v===true?'checked':''}>`; const tag=type==='textarea'?'textarea':'input'; const inputType=['number','date','email','datetime-local'].includes(type)?type:'text'; return tag==='textarea'?`<textarea data-f="${name}" rows="3">${esc(v)}</textarea>`:`<input data-f="${name}" type="${inputType}" value="${esc(v)}">`; }
  function modal(){ let m=document.getElementById('nxCrudModal'); if(!m){m=document.createElement('div');m.id='nxCrudModal';m.className='nx-modal';document.body.appendChild(m)} return m; }
  function openForm(cfg,row={}){ const m=modal(); m.innerHTML=`<div class="nx-modal-card"><div class="nx-head"><h3>${row.id?'Edit':'Tambah'} ${esc(cfg.title)}</h3><button class="secondary" data-close>×</button></div><div class="nx-form">${cfg.fields.map(([n,t])=>`<div class="${t==='textarea'?'full':''}"><label>${label(n)}${n==='name'||n==='title'||n==='full_name'?' *':''}</label>${inputFor(n,t,row[n])}</div>`).join('')}</div><div id="nxFormMsg" class="nx-muted" style="margin-top:12px"></div><div class="nx-actions" style="margin-top:12px"><button class="primary" data-save>${row.id?'Simpan Perubahan':'Simpan'}</button><button class="secondary" data-close>Batal</button></div></div>`; m.classList.add('open'); m.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>m.classList.remove('open')); m.querySelector('[data-save]').onclick=async()=>{ const payload={}; cfg.fields.forEach(([n,t])=>{const el=m.querySelector(`[data-f="${n}"]`); if(!el)return; payload[n]=t==='boolean'?el.checked:(el.value===''?null:el.value); if(t==='number'&&payload[n]!==null)payload[n]=Number(payload[n]); if(t==='uuid'&&payload[n]==='')payload[n]=null;}); if(row.id) await updateRow(cfg,row.id,payload); else await insertRow(cfg,payload); } }
  async function insertRow(cfg,payload){ const msg=document.getElementById('nxFormMsg'); const {data:org}=await sb.rpc('current_organization_id'); payload.organization_id=org; if(!payload.created_by && cfg.table==='website_campaigns') payload.created_by=(await sb.auth.getUser()).data.user?.id||null; const {error}=await sb.from(cfg.table).insert(payload); if(error){msg.textContent=error.message;return} msg.textContent='Tersimpan.'; await render(cfg); setTimeout(()=>modal().classList.remove('open'),350); }
  async function updateRow(cfg,id,payload){ const msg=document.getElementById('nxFormMsg'); const {error}=await sb.from(cfg.table).update(payload).eq('id',id); if(error){msg.textContent=error.message;return} msg.textContent='Diperbarui.'; await render(cfg); setTimeout(()=>modal().classList.remove('open'),350); }
  async function archiveRow(cfg,row){ if(!confirm(`Nonaktifkan ${row.name||row.title||row.full_name||row.unit_code||row.expense_code||row.partner_code||row.employee_code||row.campaign_code||'data ini'}?`)) return; let patch={}; if(cfg.table==='vehicle_units') patch={status:'RETIRED'}; else if(cfg.fields.some(x=>x[0]==='active')) patch={active:false}; else if(cfg.table==='employees') patch={status:'INACTIVE',end_date:new Date().toISOString().slice(0,10)}; else if(cfg.table==='partners') patch={status:'INACTIVE'}; else if(cfg.table==='social_accounts') patch={status:'INACTIVE'}; else if(cfg.table==='marketing_campaigns') patch={status:'INACTIVE'}; else return; const {error}=await sb.from(cfg.table).update(patch).eq('id',row.id); if(error)alert(error.message); else render(cfg); }
  async function render(cfg){ const host=controlHost(); if(!host)return; const old=host.querySelector('.nx-crud'); if(old)old.remove(); const ok=await can(cfg.perm); if(!ok)return; const {data,error}=await sb.from(cfg.table).select('*').order('created_at',{ascending:false}).limit(50); const box=document.createElement('section');box.className='card nx-crud'; const rows=error?[]:(data||[]); const cols=cfg.fields.slice(0,5).map(x=>x[0]); box.innerHTML=`<div class="nx-head"><div><h3>${esc(cfg.title)}</h3><div class="nx-muted">${rows.length} record terbaru · perubahan tercatat di database/audit layer</div></div><div class="nx-actions"><button class="primary" data-add>＋ Tambah</button><button class="secondary" data-refresh>↻ Refresh</button></div></div><div class="table" style="margin-top:10px"><table><thead><tr>${cols.map(c=>`<th>${label(c)}</th>`).join('')}<th>Aksi</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}<td><div class="nx-actions"><button class="secondary" data-edit="${r.id}">Edit</button>${!cfg.noDelete?`<button class="secondary" data-archive="${r.id}">Nonaktifkan</button>`:''}</div></td></tr>`).join('')||`<tr><td colspan="${cols.length+1}" class="empty">Belum ada data.</td></tr>`}</tbody></table></div>`; host.appendChild(box); box.querySelector('[data-add]').onclick=()=>openForm(cfg);box.querySelector('[data-refresh]').onclick=()=>render(cfg); box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.edit);openForm(cfg,r)}); box.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.archive);archiveRow(cfg,r)}); }
  async function tick(){ const p=activePage(); if(p===lastPage)return; lastPage=p; currentCfg=configs[p]; ensureStyle(); if(currentCfg) await render(currentCfg); }
  document.addEventListener('click',e=>{ if(e.target.closest('#nav,.submenu')) setTimeout(tick,120); });
  new MutationObserver(()=>setTimeout(tick,80)).observe(document.body,{subtree:true,childList:true});
  setInterval(tick,1000); ensureStyle();
})();
