(()=>{
const C=window.NEXUS_CONFIG||{}; if(!C.supabaseUrl||!C.supabaseAnonKey||!window.supabase)return;
const sb=supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const forms={
 customer:{label:'Customer Baru',table:'customers',fields:[['full_name','Nama Lengkap','text',1],['phone','WhatsApp / Telepon','text',1],['email','Email','email',0],['company_name','Perusahaan','text',0],['customer_type','Tipe Customer','text',1],['source_channel','Source / Channel','text',0],['notes','Catatan','textarea',0]]},
 booking:{label:'Booking Baru',table:'bookings',fields:[['customer_name','Nama Customer','text',1],['customer_phone','WhatsApp / Telepon','text',1],['vehicle_type_id','Vehicle Type ID','text',1],['service','Layanan','text',1],['start_date','Mulai','date',1],['end_date','Selesai','date',1],['area','Area','text',1],['notes','Catatan','textarea',0]]},
 unit:{label:'Unit Kendaraan Baru',table:'vehicle_units',fields:[['vehicle_type_id','Vehicle Type ID','text',1],['source_type','Sumber Unit','text',1],['partner_id','Partner ID','text',0],['unit_code','Kode Unit','text',1],['registration_number','Nomor Polisi','text',0],['manufacture_year','Tahun','number',0],['color','Warna','text',0],['status','Status','text',1],['notes','Catatan','textarea',0]]},
 payment:{label:'Pembayaran Baru',table:'payments',fields:[['booking_id','Booking ID','text',1],['amount','Jumlah','number',1],['method','Metode','text',1],['status','Status','text',1],['external_reference','Referensi Eksternal','text',0],['paid_at','Waktu Pembayaran','datetime-local',0],['notes','Catatan','textarea',0]]},
 task:{label:'Task Operasional',table:'workflow_tasks',fields:[['task_type','Jenis Task','text',1],['title','Judul','text',1],['description','Deskripsi','textarea',0],['priority','Prioritas','text',1],['status','Status','text',1],['due_at','Deadline','datetime-local',0]]},
 expense:{label:'Pengeluaran Baru',table:'expenses',fields:[['expense_code','Kode Pengeluaran','text',0],['expense_date','Tanggal','date',1],['account_id','Account ID','text',1],['cost_center_id','Cost Center ID','text',0],['description','Deskripsi','text',1],['amount','Jumlah','number',1],['vendor_name','Vendor','text',0],['status','Status','text',1],['notes','Catatan','textarea',0]]}
};
const map={customer:'customer',booking:'booking',unit:'unit',payment:'payment',task:'task',expense:'expense'};
let modal;
function style(){if(document.getElementById('nxGovStyle'))return;const s=document.createElement('style');s.id='nxGovStyle';s.textContent='.nx-gov-modal{position:fixed;inset:0;background:#000c;display:none;align-items:center;justify-content:center;padding:18px;z-index:2000}.nx-gov-modal.open{display:flex}.nx-gov-card{width:min(820px,100%);max-height:92vh;overflow:auto;background:#101319;border:1px solid #303640;border-radius:17px;padding:22px}.nx-gov-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.nx-gov-grid .full{grid-column:1/-1}.nx-gov-grid label{display:block;font-size:11px;color:#bfc4cc}.nx-gov-grid input,.nx-gov-grid textarea{width:100%;box-sizing:border-box;margin-top:5px;background:#090c11;border:1px solid #373d48;color:#fff;border-radius:9px;padding:10px}.nx-gov-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:15px}.nx-gov-error{min-height:20px;color:#ef7777;font-size:11px}@media(max-width:650px){.nx-gov-grid{grid-template-columns:1fr}.nx-gov-grid .full{grid-column:auto}}';document.head.appendChild(s)}
function open(kind){const d=forms[kind];if(!d)return;style();if(!modal){modal=document.createElement('div');modal.className='nx-gov-modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="nx-gov-card"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:10px;color:#c9a85c;letter-spacing:.12em">GOVERNED DATA ENTRY</div><h2 style="margin:5px 0 16px">${esc(d.label)}</h2></div><button type="button" data-close>×</button></div><form><div class="nx-gov-grid">${d.fields.map(([k,l,t,r])=>`<div class="${t==='textarea'?'full':''}"><label>${esc(l)}${r?' *':''}</label>${t==='textarea'?`<textarea data-k="${k}" rows="3" ${r?'required':''}></textarea>`:`<input data-k="${k}" type="${t}" ${r?'required':''}>`}</div>`).join('')}</div><div class="nx-gov-error" data-error></div><div class="nx-gov-actions"><button type="button" data-close>Batal</button><button class="primary" type="submit">Simpan</button></div></form></div>`;modal.classList.add('open');modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.classList.remove('open'));modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const payload={};d.fields.forEach(([k,,t])=>{let v=modal.querySelector(`[data-k="${k}"]`).value;if(v==='')v=null;if(t==='number'&&v!==null)v=Number(v);payload[k]=v});try{const{data,error}=await sb.rpc('manual_data_action',{p_table:d.table,p_action:'insert',p_row_id:null,p_data:payload});if(error)throw error;modal.querySelector('[data-error]').style.color='#65d49a';modal.querySelector('[data-error]').textContent=`Tersimpan. Change ID: ${data?.change_id||'-'}`;window.dispatchEvent(new CustomEvent('nexus:data-changed',{detail:{table:d.table,result:data}}));setTimeout(()=>modal.classList.remove('open'),800)}catch(err){modal.querySelector('[data-error]').textContent=err.message||'Gagal menyimpan data.'}}}
function intercept(e){const b=e.target.closest?.('.nx-quick [data-q]');if(!b)return;const k=map[b.dataset.q];if(!k)return;e.preventDefault();e.stopImmediatePropagation();open(k)}
function boot(){document.addEventListener('click',intercept,true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
