/* Nexus relational CRUD workspace: legacy shell preserved. */
(()=>{'use strict';
let db,reg=new Map(),cache={};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nice=s=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const rel={vehicle_id:['vehicles','name'],unit_id:['vehicle_units','unit_code'],vehicle_unit_id:['vehicle_units','unit_code'],booking_id:['bookings','booking_code'],customer_id:['customers','full_name'],driver_id:['drivers','full_name'],partner_id:['partners','name'],transaction_id:['transactions','transaction_code'],cost_center_id:['nexus_cost_centers','name'],org_unit_id:['nexus_org_units','name'],business_unit_id:['nexus_business_units','name'],employee_id:['nexus_employees','full_name']};
const cfg=()=>window.NEXUS_CONFIG||{};
function client(){if(db)return db;if(window.getTransmindSupabaseClient)db=window.getTransmindSupabaseClient();else db=supabase.createClient(cfg().supabaseUrl,cfg().supabaseAnonKey);return db}
function type(f){if(f.type==='boolean')return'boolean';if(['integer','bigint','numeric','real','double precision'].includes(f.type))return'number';if(f.type==='date')return'date';if(f.type.includes('timestamp'))return'datetime-local';if(f.type==='jsonb')return'json';if(f.type==='ARRAY')return'array';return'text'}
async function boot(){db=client();if(!db)return;const q=await db.from('nexus_module_registry').select('*').order('sort_order');if(q.error)return console.error(q.error);(q.data||[]).forEach(x=>reg.set(x.module_id,x));addSpecial();hook()}
function addSpecial(){const nav=document.getElementById('nav'),pages=document.getElementById('pages');if(!nav||!pages)return;const groups=[...nav.querySelectorAll('.nav-section')],crm=groups.find(x=>x.textContent.includes('Customer / CRM')),mg=groups.find(x=>x.textContent.includes('Management'));if(crm&&!crm.querySelector('[data-page="crm-command"]'))crm.querySelector('.submenu')?.insertAdjacentHTML('beforeend','<button data-page="crm-command" type="button">CRM Command Center</button>');if(mg&&!mg.querySelector('[data-page="seo-live"]'))mg.querySelector('.submenu')?.insertAdjacentHTML('beforeend','<button data-page="seo-live" type="button">SEO & Live Traffic</button>');pages.insertAdjacentHTML('beforeend','<section id="page-crm-command" class="page"><div class="hero"><div><div class="eyebrow">CUSTOMER / CRM</div><div class="title">CRM Command Center</div><div class="desc">Customer master, booking, demand dan follow-up dalam satu command center.</div></div></div><div id="crmBody"></div></section><section id="page-seo-live" class="page"><div class="hero"><div><div class="eyebrow">SEO & DIGITAL DEMAND</div><div class="title">SEO & Live Traffic Command Center</div><div class="desc">Traffic, organic, WhatsApp, booking dan conversion dari data nyata.</div></div><div class="hero-actions"><button class="secondary" data-seo="1">24 Jam</button><button class="secondary" data-seo="7">7 Hari</button><button class="secondary" data-seo="30">30 Hari</button></div></div><div id="seoBody"></div></section>');document.querySelectorAll('[data-seo]').forEach(b=>b.onclick=()=>seo(+b.dataset.seo))}
function hook(){const nav=document.getElementById('nav');if(!nav)return;nav.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;const id=b.dataset.page;if(id==='crm-command'||id==='seo-live'||reg.has(id)){e.preventDefault();e.stopImmediatePropagation();id==='crm-command'?special('crm-command'):id==='seo-live'?special('seo-live'):workspace(id)}},true)}
function special(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-'+id)?.classList.add('active');document.getElementById('breadcrumb').textContent=id==='seo-live'?'SEO / Live Traffic':'Customer / CRM / Command Center';id==='crm-command'?crm():seo(7)}
function page(id){if(document.getElementById('page-'+id))return;const r=reg.get(id);document.getElementById('pages').insertAdjacentHTML('beforeend','<section id="page-'+esc(id)+'" class="page"><div class="hero"><div><div class="eyebrow">'+esc(r.group_name)+'</div><div class="title">'+esc(r.module_label)+'</div><div class="desc">'+esc(r.description||'Relational application workspace.')+'</div></div><div class="hero-actions"><span class="status">'+(r.mode==='crud'?'● APPLICATION FORM':'● READ ONLY')+'</span></div></div><div id="ws-'+id+'"></div></section>')}
async function workspace(id){const r=reg.get(id);if(!r)return;page(id);document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-'+id).classList.add('active');document.getElementById('breadcrumb').textContent=r.group_name+' / '+r.module_label;await list(id)}
async function relations(r){for(const x of r.relation_meta||[]){if(!cache[x.target_table]){const q=await db.from(x.target_table).select('*').limit(500);if(!q.error)cache[x.target_table]=q.data||[]}}}
function relOf(f,r){const x=(r.relation_meta||[]).find(z=>z.column===f.name),t=x?.target_table||rel[f.name]?.[0];return t?[t,rel[t]?.[1]||rel[f.name]?.[1]||'name']:null}
function input(f,row,r){const t=type(f),v=row?.[f.name],rr=relOf(f,r);if(rr){const opts=cache[rr[0]]||[];return '<div class="field"><label>'+esc(nice(f.name))+(f.nullable?'':' *')+'</label><select data-f="'+esc(f.name)+'" '+(f.nullable?'':'required')+'><option value="">— pilih —</option>'+opts.map(x=>{const id=x.id??x[0];return '<option value="'+esc(id)+'" '+(String(id)===String(v)?'selected':'')+'>'+esc(x[rr[1]]||x.name||x.full_name||x.booking_code||x.unit_code||id)+'</option>'}).join('')+'</select></div>'}
if(t==='boolean')return '<div class="field"><label>'+esc(nice(f.name))+'</label><select data-f="'+f.name+'"><option value="true" '+(v===true?'selected':'')+'>Ya</option><option value="false" '+(v===false?'selected':'')+'>Tidak</option></select></div>';
if(t==='json'||t==='array')return '<div class="field form-full"><label>'+esc(nice(f.name))+'</label><textarea data-f="'+f.name+'" rows="4">'+esc(v==null?'':JSON.stringify(v))+'</textarea></div>';
const long=t==='text'&&String(v||'').length>160;return '<div class="field '+(long?'form-full':'')+'"><label>'+esc(nice(f.name))+(f.nullable?'':' *')+'</label>'+(long?'<textarea data-f="'+f.name+'" rows="5" '+(f.nullable?'':'required')+'>'+esc(v??'')+'</textarea>':'<input data-f="'+f.name+'" type="'+t+'" value="'+esc(t==='datetime-local'&&v?String(v).slice(0,16):v??'')+'" '+(f.nullable?'':'required')+'>')+'</div>'}
async function form(id,row){const r=reg.get(id),h=document.getElementById('ws-'+id);await relations(r);const fs=(r.field_meta||[]).filter(f=>!['id','created_at','updated_at'].includes(f.name));h.innerHTML='<div class="card"><div class="toolbar"><b>'+(row?'Edit Data':'Data Baru')+'</b><span class="muted">'+esc(r.table_name)+'</span></div><form id="f-'+id+'"><div class="form-grid">'+fs.map(f=>input(f,row,r)).join('')+'</div><div id="m-'+id+'" class="msg"></div><div class="toolbar"><button class="primary" type="submit">'+(row?'Update':'Insert')+'</button><button class="secondary" type="button" id="c-'+id+'">Cancel</button>'+(row?'<button class="secondary" type="button" id="d-'+id+'">Delete</button>':'')+'</div></form></div>';document.getElementById('c-'+id).onclick=()=>list(id);document.getElementById('f-'+id).onsubmit=e=>{e.preventDefault();save(id,row)};if(row)document.getElementById('d-'+id).onclick=()=>del(id,row)}
function collect(id){const r=reg.get(id),o={};document.querySelectorAll('#f-'+id+' [data-f]').forEach(el=>{const f=r.field_meta.find(x=>x.name===el.dataset.f),t=type(f);let v=el.value;if(v==='')v=null;else if(t==='boolean')v=v==='true';else if(t==='number')v=Number(v);else if(t==='json'||t==='array'){try{v=JSON.parse(v)}catch(e){throw Error(f.name+' harus JSON valid')}}else if(t==='datetime-local')v=new Date(v).toISOString();o[f.name]=v});return o}
async function save(id,row){const r=reg.get(id),m=document.getElementById('m-'+id);try{const data=collect(id),q=row?await db.from(r.table_name).update(data).eq(r.pk_column,row[r.pk_column]):await db.from(r.table_name).insert(data);if(q.error)throw q.error;m.textContent=row?'Update berhasil.':'Insert berhasil.';m.className='msg ok';setTimeout(()=>list(id),300)}catch(e){m.textContent=e.message;m.className='msg bad'}}
async function del(id,row){const r=reg.get(id);if(!confirm('Hapus record ini? Foreign key/RLS akan tetap melindungi data terkait.'))return;const q=await db.from(r.table_name).delete().eq(r.pk_column,row[r.pk_column]);if(q.error){alert(q.error.message);return}list(id)}
async function list(id){const r=reg.get(id),h=document.getElementById('ws-'+id);if(!h)return;let q=await db.from(r.table_name).select('*').limit(500);if(q.error){h.innerHTML='<div class="notice bad">'+esc(q.error.message)+'</div>';return}let rows=q.data||[];if(r.filter_column)rows=rows.filter(x=>String(x[r.filter_column])===String(r.filter_value));const fs=(r.field_meta||[]).filter(f=>!['id','created_at','updated_at'].includes(f.name)).slice(0,5);h.innerHTML='<div class="toolbar"><input id="s-'+id+'" placeholder="Cari '+esc(r.module_label)+'..."><button class="primary" id="n-'+id+'" '+(r.mode==='crud'?'':'disabled')+'>＋ Data Baru</button><button class="secondary" id="r-'+id+'">↻ Refresh</button></div><div id="t-'+id+'" class="table"></div>';const draw=a=>{document.getElementById('t-'+id).innerHTML='<div class="tr th"><span>KEY</span>'+fs.map(f=>'<span>'+esc(nice(f.name))+'</span>').join('')+'<span>ACTION</span></div>'+a.map(x=>'<div class="tr"><b>'+esc(String(x[r.pk_column]??'').slice(0,10))+'</b>'+fs.map(f=>'<span>'+esc(String(x[f.name]??'').slice(0,80))+'</span>').join('')+'<span>'+(r.mode==='crud'?'<button class="secondary" data-e="'+esc(x[r.pk_column])+'">Edit</button> <button class="secondary" data-d="'+esc(x[r.pk_column])+'">Delete</button>':'<span class="chip">View</span>')+'</span></div>').join('')+(a.length?'':'<div class="empty">Belum ada data.</div>')};draw(rows);document.getElementById('s-'+id).oninput=e=>{const s=e.target.value.toLowerCase();draw(rows.filter(x=>Object.values(x).some(v=>String(v??'').toLowerCase().includes(s))))};document.getElementById('r-'+id).onclick=()=>list(id);document.getElementById('n-'+id)?.addEventListener('click',()=>form(id,null));document.querySelectorAll('#t-'+id+' [data-e]').forEach(b=>b.onclick=()=>form(id,rows.find(x=>String(x[r.pk_column])===String(b.dataset.e))));document.querySelectorAll('#t-'+id+' [data-d]').forEach(b=>b.onclick=()=>del(id,rows.find(x=>String(x[r.pk_column])===String(b.dataset.d))))}
const card=(a,b,c)=>'<div class="card"><div class="k-label">'+esc(a)+'</div><div class="k-value">'+b+'</div><div class="k-note">'+esc(c)+'</div></div>';
async function crm(){const el=document.getElementById('crmBody');const cnt=async t=>(await db.from(t).select('*',{count:'exact',head:true})).count||0;const [c,b,d,e]=await Promise.all([cnt('customers'),cnt('bookings'),cnt('ai_companion_demand_signals'),cnt('website_analytics_events')]);el.innerHTML='<div class="grid">'+card('Customers',c,'Master CRM')+card('Bookings',b,'Transaksi')+card('AI Demand',d,'Intelligence')+card('Website Events',e,'Digital')+'</div><div class="notice" style="margin-top:13px">Submenu CRM memakai relasi Customer → Booking → Interaction → Follow Up → Value.</div>'}
async function seo(days){const el=document.getElementById('seoBody');try{const [a,b]=await Promise.all([db.rpc('nexus_seo_live_metrics',{p_days:days}),db.rpc('nexus_seo_funnel_metrics',{p_days:days})]);if(a.error||b.error)throw(a.error||b.error);const x=a.data||{},f=b.data||{};el.innerHTML='<div class="grid">'+card('Visitor Unik',x.unique_visitors||0,'session')+card('Page Views',x.page_views||0,'page')+card('Organic',x.organic_visitors||0,'visitor')+card('WhatsApp',x.whatsapp_clicks||0,'lead signal')+card('Booking',f.bookings||0,'booking')+card('Linked Booking',f.linked_bookings||0,'session-linked')+'</div>'}catch(e){el.innerHTML='<div class="notice bad">'+esc(e.message)+'</div>'}}
window.NEXUS_WORKSPACE={registry:reg,workspace,list,form};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300));else setTimeout(boot,300);
})();