/* TRANSMIND NEXUS — IN-PLACE APPLICATION CRUD + RELATIONAL WORKSPACE
   Keeps the legacy Nexus shell/dashboard intact. Submenus become working application forms.
*/
(function(){
'use strict';
const CRUD={
 'fleet-types':{title:'Data Kendaraan',group:'Armada',table:'vehicles',search:['name','category','slug'],fields:[
  ['name','Nama Kendaraan','text',1],['slug','Slug','text',1],['category','Kategori','text'],['capacity','Kapasitas','number'],['total_units','Total Unit','number'],['image_path','Image Path','text'],['sort_order','Urutan','number'],['active','Aktif','boolean']
 ]},
 'fleet-units':{title:'Unit Kendaraan',group:'Armada',table:'vehicle_units',search:['unit_code','status'],fields:[
  ['vehicle_id','Kendaraan','relation:vehicles:name',1],['unit_code','Kode Unit','text',1],['status','Status','text'],['active','Aktif','boolean'],['notes','Catatan','textarea']
 ]},
 'fleet-service':{title:'Harga Kendaraan',group:'Armada',table:'vehicle_prices',search:['service'],fields:[
  ['vehicle_id','Kendaraan','relation:vehicles:name',1],['service','Layanan','text',1],['daily_price','Harga Harian','number'],['active','Aktif','boolean']
 ]},
 'fleet-docs':{title:'Dokumen Kendaraan',group:'Armada',table:'vehicle_documents',search:['document_type','document_number','status'],fields:[
  ['vehicle_id','Kendaraan','relation:vehicles:name',1],['document_type','Jenis Dokumen','text',1],['document_number','Nomor Dokumen','text'],['issued_at','Tanggal Terbit','date'],['expires_at','Tanggal Berakhir','date'],['storage_path','Storage Path','text'],['status','Status','text'],['notes','Catatan','textarea']
 ]},
 'booking':{title:'Semua Booking',group:'Transaksi',table:'bookings',search:['customer_name','customer_phone','status','service'],fields:[
  ['customer_id','Pelanggan','relation:customers:full_name'],['customer_name','Nama Customer','text',1],['customer_phone','Telepon','text',1],['vehicle_id','Kendaraan','relation:vehicles:name',1],['unit_id','Unit','relation:vehicle_units:unit_code'],['service','Layanan','text',1],['start_date','Mulai','datetime-local',1],['end_date','Selesai','datetime-local',1],['area','Area','text'],['status','Status','text'],['total_price','Total Harga','number'],['notes','Catatan','textarea']
 ]},
 'crm-master':{title:'Customer Master',group:'Customer / CRM',table:'customers',search:['full_name','phone','verification_status','risk_level'],fields:[
  ['full_name','Nama Lengkap','text',1],['phone','Telepon','text',1],['nik','NIK','text'],['address','Alamat','textarea'],['current_address','Alamat Saat Ini','textarea'],['emergency_name','Kontak Darurat','text'],['emergency_phone','Telepon Darurat','text'],['emergency_relation','Hubungan','text'],['phone_verified','Telepon Terverifikasi','boolean'],['identity_verified','Identitas Terverifikasi','boolean'],['verification_status','Status Verifikasi','text'],['risk_level','Risk Level','text'],['notes','Catatan','textarea']
 ]},
 'crm-history':{title:'Riwayat Booking Customer',group:'Customer / CRM',table:'bookings',search:['customer_name','customer_phone','status'],fields:[
  ['customer_id','Pelanggan','relation:customers:full_name',1],['customer_name','Nama Customer','text'],['customer_phone','Telepon','text'],['vehicle_id','Kendaraan','relation:vehicles:name'],['unit_id','Unit','relation:vehicle_units:unit_code'],['service','Layanan','text'],['start_date','Mulai','datetime-local'],['end_date','Selesai','datetime-local'],['status','Status','text'],['total_price','Total Harga','number'],['notes','Catatan','textarea']
 ]},
 'sales-pipeline':{title:'Sales Pipeline',group:'Sales & Marketing',table:'nexus_growth_opportunities',search:['opportunity_key','channel','query_or_theme','status'],fields:[
  ['opportunity_key','Opportunity Key','text',1],['channel','Channel','text',1],['intent_level','Intent Level','text'],['source_type','Source Type','text'],['query_or_theme','Query / Theme','text'],['landing_path','Landing Path','text'],['recommended_action','Recommended Action','textarea'],['status','Status','text']
 ]},
 'sales-campaign':{title:'Campaign Queue',group:'Sales & Marketing',table:'nexus_campaign_queue',search:['campaign_key','channel','campaign_type','status'],fields:[
  ['campaign_key','Campaign Key','text',1],['channel','Channel','text',1],['campaign_type','Campaign Type','text'],['objective','Objective','text'],['status','Status','text'],['policy_status','Policy Status','text'],['approval_required','Approval Required','boolean'],['human_approved','Human Approved','boolean'],['title','Title','text'],['body','Body','textarea'],['cta_label','CTA Label','text'],['landing_path','Landing Path','text'],['utm_source','UTM Source','text'],['utm_medium','UTM Medium','text'],['utm_campaign','UTM Campaign','text'],['target_audience','Target Audience','text'],['scheduled_at','Scheduled At','datetime-local'],['spend_cap','Spend Cap','number']
 ]},
 'operations-task':{title:'Operations Task',group:'Operasional',table:'nexus_operations_tasks',search:['title','task_type','priority','status'],fields:[
  ['booking_id','Booking','relation:bookings:customer_name'],['customer_id','Pelanggan','relation:customers:full_name'],['task_type','Task Type','text',1],['priority','Prioritas','text'],['status','Status','text'],['title','Judul','text',1],['notes','Catatan','textarea'],['due_at','Jatuh Tempo','datetime-local'],['assigned_to','Assigned To','text']
 ]},
 'ai':{title:'Knowledge Base',group:'AI Intelligence',table:'ai_knowledge_base',search:['domain','topic','title','language_code'],fields:[
  ['domain','Domain','text',1],['topic','Topic','text',1],['title','Judul','text',1],['content','Content','textarea',1],['country_code','Country Code','text'],['language_code','Language Code','text'],['source_type','Source Type','text'],['source_url','Source URL','text'],['freshness','Freshness','text'],['active','Aktif','boolean'],['priority','Priority','number']
 ]}
};
let sb=null, current=null, rows=[], relations={};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v==null?'':String(v);
function cfg(){return window.NEXUS_CONFIG||{}}
function ensure(){if(sb)return true; if(!window.supabase||!cfg().supabaseUrl)return false; sb=window.supabase.createClient(cfg().supabaseUrl,cfg().supabaseAnonKey); return true}
function relationSpec(type){const m=type.match(/^relation:([^:]+):(.+)$/);return m?{table:m[1],label:m[2]}:null}
async function loadRelation(type){const r=relationSpec(type);if(!r)return[]; if(relations[r.table])return relations[r.table]; const q=await sb.from(r.table).select('*').limit(1000); if(q.error)throw q.error; relations[r.table]=q.data||[];return relations[r.table]}
function input(field,row){const [name,label,type,required]=field;const val=row?.[name];const rel=relationSpec(type);
 if(rel){const opts=relations[rel.table]||[];return '<div class="field"><label>'+esc(label)+(required?' *':'')+'</label><select data-f="'+esc(name)+'" '+(required?'required':'')+'><option value="">— pilih —</option>'+opts.map(x=>'<option value="'+esc(x.id)+'" '+(String(x.id)===String(val)?'selected':'')+'>'+esc(x[rel.label]||x.name||x.full_name||x.unit_code||x.id)+'</option>').join('')+'</select></div>'}
 if(type==='boolean')return '<div class="field"><label>'+esc(label)+'</label><select data-f="'+name+'"><option value="true" '+(val===true?'selected':'')+'>Ya</option><option value="false" '+(val===false?'selected':'')+'>Tidak</option></select></div>';
 const it=type==='textarea'?'<textarea data-f="'+name+'" '+(required?'required':'')+'>'+esc(val??'')+'</textarea>':'<input data-f="'+name+'" type="'+type+'" value="'+esc(type.startsWith('datetime')&&val?String(val).slice(0,16):val??'')+'" '+(required?'required':'')+' />';
 return '<div class="field '+(type==='textarea'?'form-full':'')+'"><label>'+esc(label)+(required?' *':'')+'</label>'+it+'</div>'
}
async function renderForm(row){const c=CRUD[current];if(!c)return;for(const f of c.fields)if(relationSpec(f[2]))await loadRelation(f[2]);const host=document.getElementById('crudForm');host.innerHTML='<div class="hero"><div><div class="eyebrow">'+esc(c.group)+'</div><div class="title" style="font-size:22px">'+(row?'Edit':'Data Baru')+' — '+esc(c.title)+'</div><div class="desc">Form transaksi/data menggunakan tabel '+esc(c.table)+'. Relasi diambil dari master terkait.</div></div><div class="hero-actions"><button class="secondary" type="button" id="crudBack">← Back</button></div></div><form id="crudEditor"><div class="form-grid">'+c.fields.map(f=>input(f,row)).join('')+'</div><div id="crudMsg" class="msg"></div><div class="toolbar"><button class="primary" type="submit">'+(row?'Update':'Insert')+'</button><button class="secondary" type="button" id="crudCancel">Cancel</button>'+(row?'<button class="secondary" type="button" id="crudDelete">Delete</button>':'')+'</div></form>';
 document.getElementById('crudBack').onclick=()=>renderList();document.getElementById('crudCancel').onclick=()=>renderList();document.getElementById('crudEditor').onsubmit=async e=>{e.preventDefault();await saveRow(row)};
 if(row)document.getElementById('crudDelete').onclick=()=>deleteRow(row.id);
}
function collect(){const out={};document.querySelectorAll('#crudEditor [data-f]').forEach(el=>{let v=el.value;const f=CRUD[current].fields.find(x=>x[0]===el.dataset.f);if(!f)return;if(f[2]==='boolean')v=v==='true';else if(f[2]==='number')v=v===''?null:Number(v);else if(f[2]==='datetime-local'&&v)v=new Date(v).toISOString();out[f[0]]=v===''?null:v});return out}
async function saveRow(row){const msg=document.getElementById('crudMsg');try{msg.textContent='Menyimpan...';const data=collect();let q=row?sb.from(CRUD[current].table).update(data).eq('id',row.id):sb.from(CRUD[current].table).insert(data);const r=await q;if(r.error)throw r.error;msg.textContent=row?'Berhasil diupdate.':'Berhasil diinsert.';msg.className='msg ok';setTimeout(renderList,500)}catch(e){msg.textContent=e.message;msg.className='msg bad'}}
async function deleteRow(id){if(!confirm('Hapus data ini? Pastikan tidak menjadi referensi transaksi lain.'))return;const msg=document.getElementById('crudMsg');try{const r=await sb.from(CRUD[current].table).delete().eq('id',id);if(r.error)throw r.error;renderList()}catch(e){msg.textContent=e.message;msg.className='msg bad'}}
function rowText(x,c){return c.search.map(k=>fmt(x[k])).join(' ').toLowerCase()}
function tableHtml(c,data){const visible=c.fields.slice(0,4);return '<div class="table"><div class="tr th"><span>ID</span>'+visible.map(f=>'<span>'+esc(f[1])+'</span>').join('')+'<span>ACTION</span></div>'+data.map(x=>'<div class="tr"><b>'+esc(String(x.id).slice(0,8))+'</b>'+visible.map(f=>'<span>'+esc(fmt(x[f[0]])).slice(0,80)+'</span>').join('')+'<span><button class="secondary" data-edit="'+esc(x.id)+'">Edit</button> <button class="secondary" data-del="'+esc(x.id)+'">Delete</button></span></div>').join('')||'<div class="empty">Belum ada data.</div></div>'}
async function renderList(){const c=CRUD[current];const el=document.getElementById('content-'+current);if(!el)return;try{const q=await sb.from(c.table).select('*').limit(500);if(q.error)throw q.error;rows=q.data||[];el.innerHTML='<div class="toolbar"><input id="crudSearch" placeholder="Cari '+esc(c.title)+'..."><button class="primary" id="crudNew">＋ Data Baru</button><button class="secondary" id="crudRefresh">↻ Refresh</button></div><div id="crudList">'+tableHtml(c,rows)+'</div><div id="crudForm" class="hidden"></div>';document.getElementById('crudNew').onclick=()=>{document.getElementById('crudList').classList.add('hidden');document.querySelector('.toolbar').classList.add('hidden');document.getElementById('crudForm').classList.remove('hidden');renderForm(null)};document.getElementById('crudRefresh').onclick=renderList;document.getElementById('crudSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('crudList').innerHTML=tableHtml(c,rows.filter(x=>rowText(x,c).includes(q)));bindRows()};bindRows()
}catch(e){el.innerHTML='<div class="notice bad">Gagal membaca '+esc(c.table)+': '+esc(e.message)+'</div>'}}
function bindRows(){document.querySelectorAll('#crudList [data-edit]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>String(x.id)===String(b.dataset.edit));document.getElementById('crudList').classList.add('hidden');document.querySelector('#content-'+current+' > .toolbar').classList.add('hidden');document.getElementById('crudForm').classList.remove('hidden');renderForm(r)});document.querySelectorAll('#crudList [data-del]').forEach(b=>b.onclick=()=>deleteRow(b.dataset.del))}
function activatePage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const p=document.getElementById('page-'+id);if(p)p.classList.add('active');document.querySelectorAll('.submenu button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));const b=document.querySelector('.submenu button[data-page="'+id+'"]');if(b){document.querySelectorAll('.nav-section').forEach(x=>x.classList.remove('open'));b.closest('.nav-section')?.classList.add('open')}const meta=document.querySelector('#page-'+id+' .title');if(meta)document.getElementById('breadcrumb').textContent=(CRUD[id]?.group||'NEXUS')+' / '+(CRUD[id]?.title||id);current=id;renderList()}
function addMenuItems(){const groups=[...document.querySelectorAll('.nav-section')];const crm=groups.find(g=>g.textContent.includes('Customer / CRM'));const mg=groups.find(g=>g.textContent.includes('Management'));if(crm&&!crm.querySelector('[data-page="crm-command"]')){const b=document.createElement('button');b.type='button';b.dataset.page='crm-command';b.textContent='CRM Command Center';crm.querySelector('.submenu').appendChild(b)}if(mg&&!mg.querySelector('[data-page="seo-live"]')){const b=document.createElement('button');b.type='button';b.dataset.page='seo-live';b.textContent='SEO & Live Traffic';mg.querySelector('.submenu').appendChild(b)}}
function addPages(){const pages=document.getElementById('pages');if(!pages)return;if(!document.getElementById('page-crm-command'))pages.insertAdjacentHTML('beforeend','<section id="page-crm-command" class="page"><div class="hero"><div><div class="eyebrow">CUSTOMER / CRM</div><div class="title">CRM Command Center</div><div class="desc">Satu layar untuk customer master, booking, demand, follow-up dan nilai pelanggan.</div></div><div class="hero-actions"><button class="secondary" id="crmCmdRefresh">↻ Refresh</button></div></div><div id="crmCmdBody"></div></section>');if(!document.getElementById('page-seo-live'))pages.insertAdjacentHTML('beforeend','<section id="page-seo-live" class="page"><div class="hero"><div><div class="eyebrow">SEO & DIGITAL DEMAND</div><div class="title">SEO & Live Traffic Command Center</div><div class="desc">Traffic website, source, organic demand, WhatsApp, booking dan session-linked conversion dari data nyata.</div></div><div class="hero-actions"><button class="secondary" id="seo24">24 Jam</button><button class="secondary" id="seo7">7 Hari</button><button class="secondary" id="seo30">30 Hari</button><button class="secondary" id="seoRefresh">↻ Refresh</button></div></div><div id="seoBodyNew"></div></section>')}
async function crmCommand(){const el=document.getElementById('crmCmdBody');if(!el)return;try{const count=async(t)=>{const r=await sb.from(t).select('*',{count:'exact',head:true});return r.count||0};const [cu,bo,de,wa]=await Promise.all([count('customers'),count('bookings'),count('ai_companion_demand_signals'),count('website_analytics_events')]);const recent=await sb.from('bookings').select('*').order('created_at',{ascending:false}).limit(12);el.innerHTML='<div class="grid">'+card('Customers',cu,'Master CRM')+card('Bookings',bo,'Transaction linked')+card('AI Demand',de,'Demand intelligence')+card('Website Events',wa,'Digital activity')+'</div><div class="split" style="margin-top:13px"><div class="card"><h3>Recent Customer / Booking Activity</h3><div class="list">'+(recent.data||[]).map(x=>'<div class="list-row"><span><b>'+esc(x.customer_name||'Customer')+'</b><br><small class="muted">'+esc(x.customer_phone||'')+' · '+esc(x.service||'')+'</small></span><span class="chip">'+esc(x.status||'')+'</span></div>').join('')||'<div class="empty">Belum ada booking.</div>'+'</div></div><div class="card"><h3>CRM Flow</h3><div class="list">'+[['Lead / Demand',de],['Customer Master',cu],['Booking',bo],['Website Signals',wa]].map(x=>'<div class="list-row"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'</div></div></div>'}catch(e){el.innerHTML='<div class="notice bad">'+esc(e.message)+'</div>'}}
function card(l,v,n){return '<div class="card"><div class="k-label">'+esc(l)+'</div><div class="k-value">'+v+'</div><div class="k-note">'+esc(n)+'</div></div>'}
async function seoMetrics(days){const el=document.getElementById('seoBodyNew');if(!el)return;el.innerHTML='<div class="notice">Mengambil data SEO live...</div>';try{const [a,b]=await Promise.all([sb.rpc('nexus_seo_live_metrics',{p_days:days}),sb.rpc('nexus_seo_funnel_metrics',{p_days:days})]);if(a.error||b.error)throw(a.error||b.error);const x=a.data||{},f=b.data||{};el.innerHTML='<div class="grid">'+card('Visitor Unik',x.unique_visitors||0,'session unik')+card('Page Views',x.page_views||0,'halaman')+card('Organic',x.organic_visitors||0,(x.organic_share_pct||0).toFixed(2)+'%')+card('WhatsApp',x.whatsapp_clicks||0,'lead signal')+card('Booking',f.bookings||0,'booking event')+card('Linked Booking',f.linked_bookings||0,'session-linked')+'</div><div class="split" style="margin-top:13px"><div class="card"><h3>Conversion Funnel</h3><div class="list">'+[['Visitor',f.unique_visitors],['WhatsApp',f.whatsapp_clicks],['Booking CTA',f.booking_cta_clicks],['Booking',f.bookings],['Linked',f.linked_bookings]].map(x=>'<div class="list-row"><span>'+x[0]+'</span><b>'+Number(x[1]||0)+'</b></div>').join('')+'</div></div><div class="card"><h3>Forecast</h3><div class="list">'+[['Projected Visitor 7d',x.forecast?.projected_7d_visitors],['Projected Booking 7d',x.forecast?.projected_7d_bookings],['Projected Booking 30d',x.forecast?.projected_30d_bookings]].map(x=>'<div class="list-row"><span>'+x[0]+'</span><b>'+Number(x[1]||0)+'</b></div>').join('')+'</div></div></div>'}catch(e){el.innerHTML='<div class="notice bad">SEO metrics belum dapat diakses: '+esc(e.message)+'</div>'}}
function intercept(){document.getElementById('nav')?.addEventListener('click',function(e){const b=e.target.closest('[data-page]');if(!b)return;const id=b.dataset.page;if(id==='crm-command'||id==='seo-live'||CRUD[id]){e.stopImmediatePropagation();e.preventDefault();if(id==='crm-command'||id==='seo-live'){activateSpecial(id)}else activatePage(id)}},true)}
function activateSpecial(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const p=document.getElementById('page-'+id);if(p)p.classList.add('active');document.querySelectorAll('.submenu button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));const b=document.querySelector('.submenu button[data-page="'+id+'"]');if(b){document.querySelectorAll('.nav-section').forEach(x=>x.classList.remove('open'));b.closest('.nav-section')?.classList.add('open')}document.getElementById('breadcrumb').textContent=id==='seo-live'?'SEO / Live Traffic':'Customer / CRM / Command Center';if(id==='crm-command')crmCommand();else seoMetrics(7)}
function boot(){let n=0;const t=setInterval(()=>{n++;if(document.getElementById('nav')&&document.getElementById('pages')){ensure();addMenuItems();addPages();intercept();document.getElementById('crmCmdRefresh')?.addEventListener('click',crmCommand);document.getElementById('seo24')?.addEventListener('click',()=>seoMetrics(1));document.getElementById('seo7')?.addEventListener('click',()=>seoMetrics(7));document.getElementById('seo30')?.addEventListener('click',()=>seoMetrics(30));document.getElementById('seoRefresh')?.addEventListener('click',()=>seoMetrics(7));clearInterval(t)}if(n>100)clearInterval(t)},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();