(()=>{
const C=window.NEXUS_CONFIG||{};if(!C.supabaseUrl||!C.supabaseAnonKey||!window.supabase)return;const sb=supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defs={
 customer:{label:'Customer',table:'customers',perm:'customer.manage',archive:['verification_status','Belum Diverifikasi'],fields:[['full_name','Nama Lengkap','text',1],['phone','WhatsApp / Telepon','text',1],['nik','NIK','text',0],['address','Alamat','textarea',0],['current_address','Alamat Saat Ini','textarea',0],['emergency_name','Kontak Darurat','text',0],['emergency_phone','Telepon Darurat','text',0],['emergency_relation','Hubungan','text',0],['notes','Catatan','textarea',0]]},
 vehicle:{label:'Master Kendaraan',table:'vehicles',perm:'fleet.manage',archive:['active',false],fields:[['name','Nama Kendaraan','text',1],['slug','Slug','text',1],['category','Kategori','text',0],['capacity','Kapasitas','text',0],['active','Aktif','boolean',0],['sort_order','Urutan','number',0],['image_path','Path Foto','text',0],['total_units','Total Unit','number',1]]},
 unit:{label:'Unit Kendaraan',table:'vehicle_units',perm:'fleet.manage',archive:['status','Tidak Aktif'],fields:[['vehicle_id','Vehicle ID','uuid',1],['unit_code','Kode Unit','text',1],['status','Status','select:unit_status',1],['active','Aktif','boolean',0],['notes','Catatan','textarea',0]]},
 driver:{label:'Driver',table:'drivers',perm:'driver.manage',archive:['active',false],fields:[['driver_code','Kode Driver','text',1],['full_name','Nama Lengkap','text',1],['phone','Telepon','text',0],['status','Status','text',1],['active','Aktif','boolean',0],['notes','Catatan','textarea',0]]},
 partner:{label:'Partner',table:'partners',perm:'partner.manage',archive:['status','inactive'],fields:[['partner_code','Kode Partner','text',1],['partner_type','Tipe','select:partner_type',1],['legal_name','Nama Legal','text',0],['display_name','Nama Tampilan','text',1],['contact_name','PIC','text',0],['phone','Telepon','text',0],['email','Email','email',0],['address','Alamat','textarea',0],['city','Kota','text',0],['province','Provinsi','text',0],['status','Status','select:partner_status',1],['notes','Catatan','textarea',0]]},
 crm_task:{label:'CRM Task',table:'crm_tasks',perm:'customer.manage',archive:['status','cancelled'],fields:[['customer_id','Customer ID','uuid',0],['booking_id','Booking ID','uuid',0],['task_type','Jenis Task','text',1],['priority','Prioritas','select:priority',1],['status','Status','select:crm_status',1],['due_at','Deadline','datetime-local',0],['assigned_to','Assigned User ID','uuid',0],['title','Judul','text',1],['notes','Catatan','textarea',0],['pipeline_stage','Pipeline Stage','text',0],['next_followup_at','Follow Up Berikutnya','datetime-local',0],['quote_value','Nilai Quote','number',0]]},
 ops_task:{label:'Operations Task',table:'nexus_operations_tasks',perm:'operations.manage',archive:['status','cancelled'],fields:[['booking_id','Booking ID','uuid',0],['customer_id','Customer ID','uuid',0],['task_type','Jenis Task','text',1],['priority','Prioritas','select:priority',1],['status','Status','select:ops_status',1],['title','Judul','text',1],['notes','Catatan','textarea',0],['due_at','Deadline','datetime-local',0],['assigned_to','Assigned User ID','uuid',0]]},
 growth:{label:'Growth Action',table:'nexus_growth_actions',perm:'marketing.manage',archive:['status','cancelled'],fields:[['customer_id','Customer ID','uuid',0],['booking_id','Booking ID','uuid',0],['action_type','Jenis Action','text',1],['priority','Prioritas','select:priority',1],['status','Status','select:ops_status',1],['channel','Channel','text',1],['title','Judul','text',1],['message_body','Pesan','textarea',0],['due_at','Deadline','datetime-local',0]]},
 finance_cost:{label:'Biaya Operasional',table:'nexus_finance_costs',perm:'accounting.manage',archive:['status','cancelled'],fields:[['booking_id','Booking ID','uuid',0],['cost_type','Jenis Biaya','text',1],['source_type','Sumber','text',0],['partner_id','Partner ID','uuid',0],['vehicle_unit_id','Unit ID','uuid',0],['amount','Jumlah','number',1],['status','Status','select:finance_status',1],['notes','Catatan','textarea',0]]},
 org:{label:'Organization Unit',table:'nexus_org_units',perm:'admin.manage',archive:['active',false],fields:[['code','Kode','text',1],['name','Nama','text',1],['parent_id','Parent ID','uuid',0],['active','Aktif','boolean',0]]},
 business:{label:'Business Unit',table:'nexus_business_units',perm:'admin.manage',archive:['active',false],fields:[['code','Kode','text',1],['name','Nama','text',1],['org_unit_id','Org Unit ID','uuid',0],['active','Aktif','boolean',0]]},
 cost_center:{label:'Cost Center',table:'nexus_cost_centers',perm:'accounting.manage',archive:['active',false],fields:[['code','Kode','text',1],['name','Nama','text',1],['org_unit_id','Org Unit ID','uuid',0],['active','Aktif','boolean',0]]},
 employee:{label:'Employee',table:'nexus_employees',perm:'hr.manage',archive:['active',false],fields:[['employee_code','Kode Karyawan','text',1],['full_name','Nama Lengkap','text',1],['role_code','Role Code','text',0],['department','Department','text',0],['org_unit_id','Org Unit ID','uuid',0],['business_unit_id','Business Unit ID','uuid',0],['user_id','User ID','uuid',0],['active','Aktif','boolean',0]]},
 budget:{label:'Budget',table:'nexus_budgets',perm:'accounting.manage',archive:['status','CLOSED'],fields:[['fiscal_year','Tahun Fiskal','number',1],['period_month','Bulan','number',1],['cost_center_id','Cost Center ID','uuid',0],['business_unit_id','Business Unit ID','uuid',0],['category','Kategori','text',1],['budget_amount','Budget','number',1],['committed_amount','Committed','number',0],['actual_amount','Actual','number',0],['status','Status','select:budget_status',1]]}
};
const opts={unit_status:['Tersedia','Disewa','Persiapan','Maintenance','Tidak Aktif'],partner_type:['rental','owner','corporate','fleet_owner','other'],partner_status:['pending','active','suspended','inactive','terminated'],priority:['low','normal','high','urgent'],crm_status:['open','contacted','qualified','quoted','negotiation','confirmed','paid','completed','lost','cancelled'],ops_status:['open','in_progress','done','cancelled'],finance_status:['estimated','committed','actual','cancelled'],budget_status:['OPEN','LOCKED','CLOSED']};
let modal=null,permCache={};
function style(){if(document.getElementById('nxTxStyle'))return;const s=document.createElement('style');s.id='nxTxStyle';s.textContent=`.nx-tx{margin:0 0 16px}.nx-txbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0}.nx-txbar input,.nx-txbar select{background:#0b0e13;border:1px solid #363b45;color:#fff;border-radius:9px;padding:9px}.nx-txbar input{min-width:260px;flex:1}.nx-tx-table{overflow:auto}.nx-tx-table table{width:100%;border-collapse:collapse;min-width:900px}.nx-tx-table th,.nx-tx-table td{padding:9px 8px;border-bottom:1px solid #252a31;text-align:left;vertical-align:top}.nx-tx-table th{font-size:9px;color:#8e949f;text-transform:uppercase}.nx-tx-table td{font-size:11px}.nx-tx-actions{display:flex;gap:6px;flex-wrap:wrap}.nx-tx-modal{position:fixed;inset:0;background:#000b;display:none;align-items:center;justify-content:center;padding:18px;z-index:1100}.nx-tx-modal.open{display:flex}.nx-tx-card{width:min(900px,100%);max-height:92vh;overflow:auto;background:#101319;border:1px solid #272c35;border-radius:17px;padding:20px}.nx-tx-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.nx-tx-grid .full{grid-column:1/-1}.nx-tx-grid label{display:block;color:#bfc4cc;font-size:11px}.nx-tx-grid input,.nx-tx-grid select,.nx-tx-grid textarea{width:100%;margin-top:5px;background:#0b0e13;border:1px solid #363b45;color:#fff;border-radius:9px;padding:10px}.nx-tx-msg{min-height:20px;margin-top:10px;font-size:11px}.nx-audit{color:#8e949f;font-size:10px}@media(max-width:650px){.nx-tx-grid{grid-template-columns:1fr}.nx-tx-grid .full{grid-column:auto}}`;document.head.appendChild(s)}
async function can(code){if(permCache[code]!==undefined)return permCache[code];try{const{data}=await sb.rpc('has_permission',{p_permission_code:code});permCache[code]=data===true}catch{permCache[code]=false}return permCache[code]}
function inputHtml(key,label,type,required,value){let v=value??'';if(type==='textarea')return `<div class="full"><label>${esc(label)}${required?' *':''}</label><textarea data-f="${key}" rows="3">${esc(v)}</textarea></div>`;if(type==='boolean')return `<div><label>${esc(label)}</label><input data-f="${key}" type="checkbox" ${v===true?'checked':''} style="width:auto;margin-top:9px"></div>`;if(type.startsWith('select:')){const list=opts[type.slice(7)]||[];return `<div><label>${esc(label)}${required?' *':''}</label><select data-f="${key}" ${required?'required':''}><option value="">Pilih…</option>${list.map(x=>`<option value="${esc(x)}" ${String(v)===String(x)?'selected':''}>${esc(x)}</option>`).join('')}</select></div>`}const t=['number','date','email','datetime-local'].includes(type)?type:'text';return `<div><label>${esc(label)}${required?' *':''}</label><input data-f="${key}" type="${t}" value="${esc(v)}" ${required?'required':''}></div>`}
function txModal(){if(!modal){modal=document.createElement('div');modal.id='nxTxModal';modal.className='nx-tx-modal';document.body.appendChild(modal)}return modal}
async function write(table,action,rowId,payload){const{data,error}=await sb.rpc('manual_data_action',{p_table_name:table,p_action:action,p_row_id:rowId||null,p_payload:payload||{}});if(error)throw error;return data}
async function rows(cfg){let q=sb.from(cfg.table).select('*').limit(250);const{data,error}=await q;return error?Promise.reject(error):(data||[])}
function valFor(r,key){const v=r?.[key];if(v===null||v===undefined)return '';if(typeof v==='object')return JSON.stringify(v);return v}
async function openForm(name,row){const cfg=defs[name];if(!cfg||!(await can(cfg.perm)))return;const m=txModal();m.innerHTML=`<div class="nx-tx-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><div class="eyebrow">TRANSACTIONAL WORKSPACE</div><h2 style="margin:4px 0">${row?.id?'Edit':'Tambah'} ${esc(cfg.label)}</h2><div class="nx-audit">Semua write melewati governed RPC + audit trail.</div></div><button class="secondary" data-close>×</button></div><div class="nx-tx-grid" style="margin-top:16px">${cfg.fields.map(([k,l,t,req])=>inputHtml(k,l,t,req,valFor(row,k))).join('')}</div><div class="nx-tx-msg" id="nxTxMsg"></div><div class="nx-tx-actions" style="justify-content:flex-end;margin-top:12px"><button class="secondary" data-close>Batal</button><button class="primary" data-save>${row?.id?'Simpan Perubahan':'Simpan'}</button></div></div>`;m.classList.add('open');m.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>m.classList.remove('open'));m.querySelector('[data-save]').onclick=async()=>{const msg=m.querySelector('#nxTxMsg');const payload={};for(const[k,,t,req]of cfg.fields){const el=m.querySelector(`[data-f="${k}"]`);if(!el)continue;if(t==='boolean')payload[k]=el.checked;else{let v=el.value;if(v==='')v=null;if(t==='number'&&v!==null)v=Number(v);payload[k]=v}if(req&&(payload[k]===null||payload[k]==='')){msg.textContent=`Field wajib: ${k}`;return}}try{await write(cfg.table,row?.id?'update':'insert',row?.id||null,payload);msg.className='nx-tx-msg ok';msg.textContent='Tersimpan melalui NEXUS governed CRUD.';await render(name);setTimeout(()=>m.classList.remove('open'),450)}catch(e){msg.className='nx-tx-msg bad';msg.textContent=e.message||String(e)}}}
async function archive(name,row){const cfg=defs[name];if(!cfg?.archive||!row?.id)return;if(!confirm(`Nonaktifkan/arsipkan ${cfg.label} ini?`))return;const payload={[cfg.archive[0]]:cfg.archive[1]};try{await write(cfg.table,'update',row.id,payload);await render(name)}catch(e){alert(e.message||String(e))}}
async function remove(name,row){const cfg=defs[name];if(!row?.id)return;const role=(document.getElementById('role')?.textContent||'').toLowerCase();if(!['owner','admin','director'].includes(role))return alert('Penghapusan permanen hanya untuk owner/admin/director.');if(!confirm(`HAPUS PERMANEN ${cfg.label}? Histori bisnis akan tetap tercatat melalui audit.`))return;try{await write(cfg.table,'delete',row.id,{});await render(name)}catch(e){alert(e.message||String(e))}}
function pageIds(){return [...document.querySelectorAll('.page')].map(x=>x.id.replace(/^page-/,'')).filter(Boolean)}
const quick={booking:['booking'],booking-new:['booking'],crm:['customer','crm_task'],crm-master:['customer'],crm-followup:['crm_task'],fleet:['vehicle','unit'],fleet-types:['vehicle'],fleet-units:['unit'],partner:['partner'],partner-master:['partner'],finance:['finance_cost'],finance-cost:['finance_cost'],operations:['ops_task'],operations-task:['ops_task'],sales:['growth'],sales-pipeline:['crm_task','growth'],procurement:['budget'],procurement-pr:['budget'],hr:['employee'],hr-employee:['employee'],admin-org:['org','business'],admin-system:['cost_center'],admin-audit:[],reports:['finance_cost']};
function quickButtons(id){const names=quick[id]||[];if(!names.length)return '';return `<div class="nx-txbar nx-tx"><span class="nx-audit">Transaksi / master data</span>${names.map(n=>`<button class="${n==='booking'?'primary':'secondary'}" data-tx-add="${n}">＋ ${esc(defs[n].label)}</button>`).join('')}</div>`}
async function render(name){const cfg=defs[name];if(!cfg||!(await can(cfg.perm)))return;const host=document.getElementById('content-'+(name==='customer'?'crm-master':name==='vehicle'?'fleet-types':name==='unit'?'fleet-units':name==='partner'?'partner-master':name==='employee'?'hr-employee':name==='ops_task'?'operations-task':name==='crm_task'?'crm-followup':name==='finance_cost'?'finance-cost':name));if(!host)return;let data=[];try{data=await rows(cfg)}catch(e){host.innerHTML=`<div class="notice bad">Gagal membaca ${esc(cfg.label)}: ${esc(e.message)}</div>`;return}const cols=cfg.fields.slice(0,6).map(x=>x[0]);host.innerHTML=`${quickButtons(name)}<div class="card nx-tx"><div class="nx-txbar"><input data-search placeholder="Cari ${esc(cfg.label)}…"><button class="primary" data-add>＋ Tambah</button><button class="secondary" data-refresh>↻ Refresh</button></div><div class="nx-tx-table"><table><thead><tr>${cols.map(c=>`<th>${esc(c.replace(/_/g,' '))}</th>`).join('')}<th>Aksi</th></tr></thead><tbody>${data.map(r=>`<tr data-row><td>${cols.map(c=>`<td>${esc(valFor(r,c))}</td>`).join('')}<td><div class="nx-tx-actions"><button class="secondary" data-edit="${r.id}">Edit</button>${cfg.archive?`<button class="secondary" data-archive="${r.id}">Arsip</button>`:''}<button class="secondary" data-delete="${r.id}">Hapus</button></div></td></tr>`).join('')||`<tr><td colspan="${cols.length+1}" class="empty">Belum ada data.</td></tr>`}</tbody></table></div></div>`;host.querySelector('[data-add]').onclick=()=>openForm(name);host.querySelector('[data-refresh]').onclick=()=>render(name);host.querySelector('[data-search]').oninput=e=>{const q=e.target.value.toLowerCase();host.querySelectorAll('[data-row]').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')};host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(name,data.find(r=>r.id===b.dataset.edit)));host.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archive(name,data.find(r=>r.id===b.dataset.archive)));host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(name,data.find(r=>r.id===b.dataset.delete)))}
function wire(){style();const observer=new MutationObserver(()=>{for(const id of pageIds()){const names=quick[id]||[];for(const n of names){if(document.getElementById('content-'+id)?.querySelector(`[data-tx-add="${n}"]`))continue;const host=document.getElementById('content-'+id);if(host&&!host.querySelector('.nx-tx')){const b=quickButtons(id);if(b)host.insertAdjacentHTML('afterbegin',b);host.querySelectorAll('[data-tx-add]').forEach(x=>x.onclick=()=>x.dataset.txAdd==='booking'&&window.openBooking?window.openBooking():openForm(x.dataset.txAdd))}}}});const p=document.getElementById('pages');if(p)observer.observe(p,{childList:true,subtree:true});document.addEventListener('click',e=>{const b=e.target.closest('[data-tx-add]');if(!b)return;if(b.dataset.txAdd==='booking'&&window.openBooking)window.openBooking();else openForm(b.dataset.txAdd)});for(const id of pageIds())for(const n of quick[id]||[]){if(defs[n])render(n)}window.addEventListener('nexus:data-changed',()=>{for(const n of Object.keys(defs))render(n)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();