(()=>{
const CFG=window.NEXUS_CONFIG||{}; if(!CFG.supabaseUrl||!CFG.supabaseAnonKey||!window.supabase)return;
const sb=supabase.createClient(CFG.supabaseUrl,CFG.supabaseAnonKey);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defs={
 booking:{label:'Booking Baru',table:'bookings',perm:'operations.manage',fields:[['customer_name','Nama Customer','text',1],['customer_phone','WhatsApp / Telepon','text',1],['vehicle_type_id','Tipe Kendaraan','vehicle',1],['service','Layanan','service',1],['start_at','Mulai','datetime-local',1],['end_at','Selesai','datetime-local',1],['area','Area','text',1],['buffer_minutes','Buffer (menit)','number',0],['notes','Catatan','textarea',0]]},
 customer:{label:'Customer Baru',table:'customers',perm:'customer.manage',fields:[['customer_code','Kode Customer','text',0],['full_name','Nama Lengkap','text',1],['phone','WhatsApp / Telepon','text',1],['email','Email','email',0],['company_name','Perusahaan','text',0],['customer_type','Tipe Customer','customer_type',1],['source_channel','Source / Channel','text',0],['notes','Catatan','textarea',0]]},
 driver:{label:'Driver Baru',table:'drivers',perm:'driver.manage',fields:[['driver_code','Kode Driver','text',0],['full_name','Nama Lengkap','text',1],['phone','Telepon','text',0],['email','Email','email',0],['source_type','Sumber','driver_source',1],['sim_type','Jenis SIM','text',0],['sim_expires_at','SIM Berlaku Sampai','date',0],['sim_status','Status SIM','sim_status',0],['photo_url','URL Foto','text',0],['notes','Catatan','textarea',0]]},
 unit:{label:'Unit Kendaraan Baru',table:'vehicle_units',perm:'fleet.manage',fields:[['vehicle_type_id','Tipe Kendaraan','vehicle',1],['source_type','Sumber Unit','unit_source',1],['partner_id','Partner','partner',0],['unit_code','Kode Unit','text',1],['registration_number','Nomor Polisi','text',0],['manufacture_year','Tahun','number',0],['color','Warna','text',0],['status','Status','unit_status',1],['notes','Catatan','textarea',0]]},
 expense:{label:'Pengeluaran Baru',table:'expenses',perm:'accounting.manage',fields:[['expense_code','Kode Pengeluaran','text',0],['expense_date','Tanggal','date',1],['account_id','Akun Biaya','account',1],['cost_center_id','Cost Center','cost_center',0],['description','Deskripsi','text',1],['amount','Jumlah','number',1],['vendor_name','Vendor','text',0],['status','Status','expense_status',1],['notes','Catatan','textarea',0]]},
 payment:{label:'Pembayaran Baru',table:'payments',perm:'accounting.manage',fields:[['booking_id','Booking','booking',1],['amount','Jumlah','number',1],['method','Metode','payment_method',1],['status','Status','payment_status',1],['external_reference','Referensi Eksternal','text',0],['paid_at','Waktu Pembayaran','datetime-local',0],['notes','Catatan','textarea',0]]},
 task:{label:'Task Operasional',table:'workflow_tasks',perm:'operations.manage',fields:[['task_type','Jenis Task','text',1],['title','Judul','text',1],['description','Deskripsi','textarea',0],['priority','Prioritas','priority',1],['status','Status','task_status',1],['due_at','Deadline','datetime-local',0]]},
 demand:{label:'Demand / Request Baru',table:'demand_requests',perm:'sales.view',fields:[['customer_name','Nama Customer','text',1],['customer_phone','Telepon','text',1],['vehicle_type_id','Tipe Kendaraan','vehicle',0],['service','Layanan','service',1],['requested_start_at','Mulai','datetime-local',1],['requested_end_at','Selesai','datetime-local',1],['area','Area','text',1],['source_channel','Source','text',0],['notes','Catatan','textarea',0]]},
 attendance:{label:'Absensi Baru',table:'employee_attendance',perm:'hr.manage',fields:[['employee_id','Karyawan','employee',1],['attendance_date','Tanggal','date',1],['check_in','Check In','datetime-local',0],['check_out','Check Out','datetime-local',0],['status','Status','attendance_status',1],['notes','Catatan','textarea',0]]},
 inventory:{label:'Pergerakan Stok',table:'inventory_movements',perm:'inventory.manage',fields:[['item_id','Item','inventory',1],['movement_type','Jenis Pergerakan','movement_type',1],['quantity','Jumlah','number',1],['reference_type','Referensi','text',0],['notes','Catatan','textarea',0]]},
 purchase:{label:'Purchase Request',table:'purchase_requests',perm:'procurement.manage',fields:[['request_code','Kode Request','text',0],['description','Kebutuhan','textarea',1],['estimated_amount','Estimasi','number',1],['cost_center_id','Cost Center','cost_center',0],['needed_by','Dibutuhkan Tanggal','date',0],['status','Status','purchase_status',1],['notes','Catatan','textarea',0]]},
 ar:{label:'Invoice Customer',table:'ar_invoices',perm:'accounting.manage',fields:[['invoice_number','Nomor Invoice','text',0],['customer_id','Customer','customer',0],['booking_id','Booking','booking',0],['invoice_date','Tanggal Invoice','date',1],['due_date','Jatuh Tempo','date',0],['subtotal','Subtotal','number',1],['discount_amount','Diskon','number',0],['tax_amount','Pajak','number',0],['total_amount','Total','number',1],['status','Status','ar_status',1],['notes','Catatan','textarea',0]]},
 ap:{label:'Bill Vendor / Partner',table:'ap_bills',perm:'accounting.manage',fields:[['bill_number','Nomor Bill','text',0],['vendor_id','Vendor','vendor',0],['partner_id','Partner','partner',0],['bill_date','Tanggal Bill','date',1],['due_date','Jatuh Tempo','date',0],['subtotal','Subtotal','number',1],['tax_amount','Pajak','number',0],['total_amount','Total','number',1],['status','Status','ap_status',1],['notes','Catatan','textarea',0]]}
};
const opts={service:['Self Drive','Dengan Driver','Airport Transfer','Drop Off','Pariwisata','Corporate','Wedding','Other'],customer_type:['INDIVIDUAL','CORPORATE','PARTNER','AGENT','OTHER'],driver_source:['OWN','PARTNER','FREELANCE'],sim_status:['UNKNOWN','VALID','EXPIRING','EXPIRED','SUSPENDED'],unit_source:['OWN','PARTNER'],unit_status:['AVAILABLE','BOOKED','RENTED','MAINTENANCE','INACTIVE','RESERVED'],expense_status:['DRAFT','SUBMITTED','APPROVED','PAID','CANCELLED'],payment_method:['BANK_TRANSFER','CASH','CARD','E_WALLET','PAYMENT_GATEWAY','OTHER'],payment_status:['PENDING','AUTHORIZED','PAID','FAILED','REFUNDED','CANCELLED'],priority:['LOW','NORMAL','HIGH','URGENT'],task_status:['OPEN','IN_PROGRESS','DONE','CANCELLED'],attendance_status:['PRESENT','LATE','ABSENT','LEAVE','REMOTE'],movement_type:['IN','OUT','ADJUSTMENT'],purchase_status:['DRAFT','SUBMITTED','APPROVED','REJECTED','CANCELLED'],ar_status:['DRAFT','ISSUED','PARTIAL','PAID','OVERDUE','VOID'],ap_status:['DRAFT','RECEIVED','APPROVED','PARTIAL','PAID','OVERDUE','VOID']};
const refMap={vehicle:['vehicle_types','id,name','active.eq.true'],partner:['partners','id,name','status.eq.ACTIVE'],booking:['bookings','id,booking_code,customer_name',''],customer:['customers','id,full_name','status.eq.ACTIVE'],employee:['employees','id,full_name','status.eq.ACTIVE'],inventory:['inventory_items','id,name','active.eq.true'],vendor:['vendors','id,name','status.eq.ACTIVE'],account:['ledger_accounts','id,code,name','active.eq.true'],cost_center:['cost_centers','id,code,name','active.eq.true']};
let modal;
function ensureStyle(){if(document.getElementById('nxManualStyle'))return;const s=document.createElement('style');s.id='nxManualStyle';s.textContent='.nx-quick{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 15px}.nx-quick button{background:#0d1015;color:#e7e8eb;border:1px solid #343943;border-radius:10px;padding:8px 10px;font-size:11px}.nx-quick button.primary{background:var(--gold);color:#111;border-color:var(--gold);font-weight:800}.nx-manual-modal{position:fixed;inset:0;background:#000b;display:none;align-items:center;justify-content:center;padding:18px;z-index:1000}.nx-manual-modal.open{display:flex}.nx-manual-card{width:min(850px,100%);max-height:92vh;overflow:auto;background:#101319;border:1px solid #272c35;border-radius:17px;padding:21px}.nx-manual-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.nx-manual-grid .full{grid-column:1/-1}.nx-manual-grid label{display:block;color:#bfc4cc;font-size:11px}.nx-manual-grid input,.nx-manual-grid select,.nx-manual-grid textarea{width:100%;margin-top:5px;background:#0b0e13;border:1px solid #363b45;color:#fff;border-radius:9px;padding:10px}.nx-manual-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.nx-manual-foot{display:flex;gap:8px;margin-top:14px;justify-content:flex-end}.nx-manual-msg{min-height:20px;font-size:11px;color:#e87878}@media(max-width:650px){.nx-manual-grid{grid-template-columns:1fr}.nx-manual-grid .full{grid-column:auto}}';document.head.appendChild(s)}
function modalEl(){if(!modal){modal=document.createElement('div');modal.className='nx-manual-modal';modal.id='nxManualModal';document.body.appendChild(modal)}return modal}
async function permitted(code){try{const{data}=await sb.rpc('has_permission',{p_permission_code:code});return data===true}catch{return false}}
async function refs(kind){const d=refMap[kind];if(!d)return[];let q=sb.from(d[0]).select(d[1]).limit(200);if(d[2]){const [field,op,val]=d[2].split('.');q=op==='eq'?q.eq(field,val):q}const{data}=await q;return data||[]}
async function control(name){const d=defs[name];if(!d||!(await permitted(d.perm)))return;const m=modalEl();const rs={};for(const[, ,type]of d.fields){if(refMap[type])rs[type]=await refs(type)}
const fieldHtml=d.fields.map(([key,label,type,req])=>{let body='';if(type==='textarea')body=`<textarea data-key="${key}" rows="3"></textarea>`;else if(opts[type])body=`<select data-key="${key}" ${req?'required':''}><option value="">Pilih…</option>${opts[type].map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`;else if(refMap[type]){body=`<select data-key="${key}" ${req?'required':''}><option value="">Pilih…</option>${(rs[type]||[]).map(x=>`<option value="${x.id}">${esc(x.name||x.full_name||x.booking_code||x.code||x.item_code||x.id)}</option>`).join('')}</select>`}else{const t=['number','date','email','datetime-local'].includes(type)?type:'text';body=`<input data-key="${key}" type="${t}" ${req?'required':''}>`}return `<div class="${type==='textarea'?'full':''}"><label>${esc(label)}${req?' *':''}</label>${body}</div>`}).join('');
m.innerHTML=`<div class="nx-manual-card"><div class="nx-manual-head"><div><div class="eyebrow">NEXUS MANUAL ENTRY</div><h2 style="margin:4px 0 0">${esc(d.label)}</h2></div><button class="secondary" data-x>×</button></div><div class="nx-manual-grid">${fieldHtml}</div><div class="nx-manual-msg" id="nxManualMsg"></div><div class="nx-manual-foot"><button class="secondary" data-x>Batal</button><button class="primary" data-save>Simpan</button></div></div>`;m.classList.add('open');m.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>m.classList.remove('open'));m.querySelector('[data-save]').onclick=async()=>{const msg=m.querySelector('#nxManualMsg');const payload={};d.fields.forEach(([key,,type])=>{const el=m.querySelector(`[data-key="${key}"]`);if(!el)return;let v=el.value;if(v==='')v=null;if(type==='number'&&v!==null)v=Number(v);payload[key]=v});const{data:org}=await sb.rpc('current_organization_id');if(org)payload.organization_id=org;const{data:{user}}=await sb.auth.getUser();if(payload.created_by===undefined&&['task','attendance','inventory','purchase','ar','ap'].includes(name))payload.created_by=user?.id||null;const{error}=await sb.from(d.table).insert(payload);if(error){msg.textContent=error.message;return}msg.style.color='#65d49a';msg.textContent='Data berhasil disimpan.';setTimeout(()=>m.classList.remove('open'),450);window.dispatchEvent(new CustomEvent('nexus:data-changed',{detail:{table:d.table}}))}}
function addQuick(){ensureStyle();const pages=document.querySelectorAll('.page');pages.forEach(p=>{if(p.querySelector('.nx-quick'))return;const id=p.id;const map={booking:['booking'],booking-new:['booking'],crm:['customer'],crm-master:['customer'],fleet:['unit','driver'],fleet-types:['unit'],fleet-units:['unit'],partner:['customer'],partner-master:['customer'],finance:['payment','expense'],finance-payment:['payment'],finance-expense:['expense'],operations:['task','booking'],hr:['attendance','driver'],hr-employee:['driver'],procurement:['purchase'],reports:['expense'],sales:['demand','customer'],sales-pipeline:['demand'],forecast:['demand'],driver:['driver'],driver-management:['driver'],accounting:['expense','payment','ar','ap']};const names=map[id];if(!names)return;const box=document.createElement('div');box.className='nx-quick';box.innerHTML=names.map(n=>`<button class="${n==='booking'?'primary':''}" data-q="${n}">＋ ${esc(defs[n].label)}</button>`).join('');const hero=p.querySelector('.hero');if(hero)hero.insertAdjacentElement('afterend',box);else p.prepend(box);box.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>control(b.dataset.q))})}
function boot(){ensureStyle();addQuick();const mo=new MutationObserver(()=>addQuick());const pages=document.getElementById('pages');if(pages)mo.observe(pages,{childList:true,subtree:true});window.addEventListener('nexus:navigation',addQuick);setInterval(addQuick,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();