(()=>{
'use strict';
const C=window.NEXUS_CONFIG||{}; if(!C.supabaseUrl||!C.supabaseAnonKey)return;
const db=supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const rup=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const dt=v=>v?new Date(v).toLocaleString('id-ID',{dateStyle:'short',timeStyle:'short'}):'—';
let mounted=false,selected=null,last=null;
function page(){return document.querySelector('.page.active')?.id||''}
function css(){if(document.getElementById('nxOpsStyle'))return;const s=document.createElement('style');s.id='nxOpsStyle';s.textContent=`.nx-ops{margin-top:16px}.nx-ops-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.nx-ops-k{padding:14px;border:1px solid #272c35;border-radius:12px;background:#0e1116}.nx-ops-k b{font-size:23px;display:block;margin-top:5px}.nx-ops-k span{font-size:9px;color:#8e949f;text-transform:uppercase;letter-spacing:.8px}.nx-ops-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-top:12px}.nx-ops-table{overflow:auto}.nx-ops-table table{width:100%;border-collapse:collapse;min-width:720px}.nx-ops-table th,.nx-ops-table td{padding:9px 7px;border-bottom:1px solid #252a31;text-align:left;font-size:11px}.nx-ops-table th{font-size:9px;color:#8e949f;text-transform:uppercase}.nx-ops-table tr.sel{background:#19150b;box-shadow:inset 2px 0 #d2ad32}.nx-ops-tools{display:flex;gap:7px;flex-wrap:wrap}.nx-ops-note{font-size:11px;color:#8e949f;line-height:1.5}.nx-ops-detail{display:grid;gap:8px}.nx-ops-detail .r{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #252a31;padding:7px 0}.nx-ops-detail .r span{color:#8e949f}.nx-ops-badge{display:inline-block;padding:4px 8px;border:1px solid #343943;border-radius:999px;font-size:10px}.nx-ops-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}@media(max-width:900px){.nx-ops-grid{grid-template-columns:repeat(2,1fr)}.nx-ops-layout{grid-template-columns:1fr}}@media(max-width:600px){.nx-ops-grid{grid-template-columns:1fr 1fr}.nx-ops-k b{font-size:19px}}`;document.head.appendChild(s)}
function host(){let h=document.querySelector('.page.active');if(!h)return null;let x=h.querySelector('.nx-ops');if(!x){x=document.createElement('section');x.className='nx-ops';h.appendChild(x)}return x}
async function load(){if(page()!=='dashboard-ops')return;css();const h=host();if(!h)return;h.innerHTML='<div class="card"><b>Operational Command Center</b><div class="nx-ops-note" style="margin-top:6px">Memuat workflow Booking → Assignment → Driver Card → Trip → Payment → Closing…</div></div>';const {data,error}=await db.rpc('nexus_ops_command_center',{p_limit:25});if(error){h.innerHTML=`<div class="card"><b>Operational Command Center</b><div class="nx-ops-note">${esc(error.message)}</div></div>`;return}last=data||{};render(h)}
function render(h){const b=last.bookings||[],a=last.assignments||[],d=last.drivers||[],c=last.cards||[],ot=last.operations_tasks||[],ct=last.crm_tasks||[];h.innerHTML=`<div class="nx-ops-grid"><div class="nx-ops-k"><span>Booking</span><b>${b.length}</b></div><div class="nx-ops-k"><span>Ops Task Open</span><b>${ot.length}</b></div><div class="nx-ops-k"><span>Assignment</span><b>${a.length}</b></div><div class="nx-ops-k"><span>Driver Aktif</span><b>${d.length}</b></div></div><div class="nx-ops-layout"><div class="card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><h3>Workflow Queue</h3><button class="secondary" data-refresh>Refresh</button></div><div class="nx-ops-table"><table><thead><tr><th>Booking</th><th>Customer</th><th>Layanan</th><th>Status</th><th>Nilai</th><th>Mulai</th></tr></thead><tbody>${b.map(x=>`<tr class="${selected===x.id?'sel':''}" data-b="${x.id}"><td>${esc(x.booking_code)}</td><td>${esc(x.customer_name)}</td><td>${esc(x.service)}</td><td><span class="nx-ops-badge">${esc(x.status)}</span></td><td>${rup(x.total_price)}</td><td>${dt(x.start_date)}</td></tr>`).join('')||'<tr><td colspan="6">Belum ada booking.</td></tr>'}</tbody></table></div></div><div class="card"><h3>Selected Workflow</h3><div class="nx-ops-detail">${detail(b.find(x=>x.id===selected),a,c)}</div></div></div><div class="card" style="margin-top:12px"><h3>Open Tasks</h3><div class="nx-ops-table"><table><thead><tr><th>Jenis</th><th>Judul</th><th>Prioritas</th><th>Jatuh Tempo</th></tr></thead><tbody>${ot.slice(0,15).map(x=>`<tr><td>${esc(x.task_type)}</td><td>${esc(x.title)}</td><td>${esc(x.priority)}</td><td>${dt(x.due_at)}</td></tr>`).join('')||'<tr><td colspan="4">Tidak ada task terbuka.</td></tr>'}</tbody></table></div><div class="nx-ops-note" style="margin-top:8px">CRM task aktif: ${ct.length}. Driver Card: ${c.length}. Driver aktif: ${d.length}. Saat ini belum ada driver/assignment produksi; tidak ada data dummy yang dibuat.</div></div>`;h.querySelector('[data-refresh]').onclick=load;h.querySelectorAll('[data-b]').forEach(r=>r.onclick=()=>{selected=r.dataset.b;render(h)})}
function detail(b,a,c){if(!b)return '<div class="nx-ops-note">Pilih satu booking untuk melihat jalur operasional.</div>';const as=a.find(x=>x.booking_id===b.id);const card=as&&c.find(x=>x.assignment_id===as.id);return `<div class="r"><span>Booking</span><b>${esc(b.booking_code)}</b></div><div class="r"><span>Customer</span><b>${esc(b.customer_name)}</b></div><div class="r"><span>Status</span><b>${esc(b.status)}</b></div><div class="r"><span>Assignment</span><b>${as?esc(as.status):'Belum ada'}</b></div><div class="r"><span>Driver Card</span><b>${card?esc(card.status):'Belum dibuat'}</b></div><div class="r"><span>Nilai</span><b>${rup(b.total_price)}</b></div><div class="nx-ops-actions">${as?`<button class="secondary" data-transition="accepted">Accept</button><button class="secondary" data-transition="started">Start Trip</button><button class="secondary" data-transition="completed">Complete</button><button class="primary" data-card>Generate Driver Card</button>`:'<span class="nx-ops-note">Assignment belum tersedia. Tambahkan driver dan lakukan dispatch untuk mengaktifkan tahap berikutnya.</span>'}</div>`}
async function action(fn,args){const {data,error}=await db.rpc(fn,args);if(error){alert(error.message);return}alert('Berhasil.');return data}
const mo=new MutationObserver(()=>{if(page()==='dashboard-ops'&&!mounted){mounted=true;load()}else if(page()!=='dashboard-ops'){mounted=false;selected=null}});mo.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});setTimeout(()=>{if(page()==='dashboard-ops'){mounted=true;load()}},1000);
})();