(function(){'use strict';
const M={
vehicles:{g:'ARMADA',n:'Data Kendaraan',h:'Master jenis kendaraan.',f:[['name','Nama','text',1],['slug','Slug','text',1],['category','Kategori','text'],['capacity','Kapasitas','text'],['total_units','Jumlah Unit','number'],['image_path','Path Gambar','text'],['sort_order','Urutan','number'],['active','Aktif','bool']]},
vehicle_units:{g:'ARMADA',n:'Unit Kendaraan',h:'Unit fisik dan status operasional.',f:[['vehicle_id','Kendaraan','vehicle',1],['unit_code','Kode Unit','text',1],['status','Status','select:Tersedia|Disewa|Persiapan|Maintenance|Tidak Aktif'],['active','Aktif','bool'],['notes','Catatan','textarea']]},
vehicle_prices:{g:'ARMADA',n:'Harga Kendaraan',h:'Harga harian per kendaraan.',f:[['vehicle_id','Kendaraan','vehicle',1],['service','Layanan','text',1],['daily_price','Harga Harian','number',1],['active','Aktif','bool']]},
rental_prices:{g:'ARMADA',n:'Tarif Rental',h:'Tarif menurut layanan dan durasi.',f:[['vehicle_id','Kendaraan','vehicle',1],['service_type','Layanan','select:lepas_kunci|dengan_driver|wedding|pariwisata',1],['duration_type','Durasi','select:harian|3_hari|mingguan|12_jam|full_day|paket',1],['duration_days','Hari','number'],['price','Harga','number',1],['area','Area','text'],['active','Aktif','bool'],['notes','Catatan','textarea']]},
vehicle_documents:{g:'ARMADA',n:'Dokumen Kendaraan',h:'STNK, KIR, pajak dan dokumen lainnya.',f:[['vehicle_id','Kendaraan','vehicle',1],['document_type','Jenis Dokumen','text',1],['document_number','Nomor','text'],['issued_at','Terbit','date'],['expires_at','Berakhir','date'],['storage_path','Path File','text'],['status','Status','select:ACTIVE|EXPIRED|PENDING'],['notes','Catatan','textarea']]},
bookings:{g:'OPERASIONAL',n:'Booking',h:'Siklus reservasi dan permintaan pelanggan.',f:[['customer_name','Nama Pelanggan','text',1],['customer_phone','WhatsApp','text',1],['customer_id','Pelanggan','customer'],['vehicle_id','Kendaraan','vehicle',1],['unit_id','Unit','unit'],['service','Layanan','text',1],['start_date','Mulai','date',1],['end_date','Selesai','date',1],['area','Area','text',1],['status','Status','select:Menunggu|Dikonfirmasi|Berjalan|Selesai|Dibatalkan'],['total_price','Total Harga','number'],['notes','Catatan','textarea']]},
customers:{g:'OPERASIONAL',n:'Pelanggan',h:'Master pelanggan dan verifikasi.',f:[['full_name','Nama Lengkap','text',1],['phone','Telepon','text',1],['nik','NIK','text'],['address','Alamat','textarea'],['current_address','Alamat Saat Ini','textarea'],['emergency_name','Kontak Darurat','text'],['emergency_phone','Telepon Darurat','text'],['emergency_relation','Hubungan','text'],['phone_verified','Telepon Terverifikasi','bool'],['identity_verified','Identitas Terverifikasi','bool'],['verification_status','Verifikasi','text'],['risk_level','Risk Level','text'],['notes','Catatan','textarea']]},
drivers:{g:'OPERASIONAL',n:'Driver',h:'Master driver.',f:[['driver_code','Kode Driver','text',1],['full_name','Nama Driver','text',1],['phone','Telepon','text'],['status','Status','text'],['active','Aktif','bool'],['notes','Catatan','textarea']]},
driver_assignments:{g:'OPERASIONAL',n:'Penugasan Driver',h:'Hubungkan booking, driver dan unit.',f:[['booking_id','Booking','booking',1],['driver_id','Driver','driver',1],['vehicle_unit_id','Unit','unit'],['status','Status','text'],['assigned_at','Ditugaskan','datetime'],['accepted_at','Diterima','datetime'],['started_at','Mulai','datetime'],['completed_at','Selesai','datetime'],['notes','Catatan','textarea']]},
transactions:{g:'KEUANGAN',n:'Transaksi',h:'Transaksi terkait booking.',f:[['transaction_code','Kode Transaksi','text',1],['booking_id','Booking','booking'],['customer_id','Pelanggan','customer'],['vehicle_id','Kendaraan','vehicle'],['unit_id','Unit','unit'],['gross_amount','Nilai Bruto','number',1],['transaction_status','Status','text'],['currency','Mata Uang','text'],['source','Sumber','text']]},
ai_companion_demand_signals:{g:'INTELLIGENCE',n:'AI Demand',h:'Demand nyata dari AI Companion.',f:[['session_id','Session','text',1],['intent','Intent','text'],['tags','Tags','array'],['destination','Tujuan','text'],['origin','Asal','text'],['passenger_count','Penumpang','number'],['duration_days','Durasi Hari','number'],['service_type','Layanan','text'],['vehicle_class','Kelas Kendaraan','text'],['demand_text','Demand','textarea',1],['source','Sumber','text'],['status','Status','select:OPEN|REVIEWED|PROMOTED|DISMISSED']]},
ai_knowledge_base:{g:'INTELLIGENCE',n:'Knowledge Base',h:'Pengetahuan yang dipakai AI.',f:[['domain','Domain','text',1],['topic','Topik','text',1],['title','Judul','text',1],['content','Isi','textarea',1],['country_code','Negara','text'],['language_code','Bahasa','text'],['source_type','Sumber','text'],['source_url','URL','text'],['freshness','Freshness','text'],['active','Aktif','bool'],['priority','Prioritas','number']]},
ai_destination_knowledge:{g:'INTELLIGENCE',n:'Destinasi',h:'Master destinasi travel concierge.',f:[['country_code','Kode Negara','text'],['country_name','Negara','text',1],['region_name','Region','text'],['city_name','Kota/Destinasi','text',1],['destination_type','Tipe','text'],['latitude','Latitude','number'],['longitude','Longitude','number'],['timezone','Timezone','text'],['best_for','Best For','array'],['description','Deskripsi','textarea'],['active','Aktif','bool'],['source_type','Sumber','text'],['source_url','URL','text']]},
nexus_growth_opportunities:{g:'GROWTH',n:'Growth Opportunities',h:'Peluang SEO, content dan lead.',f:[['opportunity_key','Opportunity Key','text',1],['channel','Channel','text',1],['intent_level','Intent','text',1],['source_type','Source','text',1],['query_or_theme','Query/Theme','text',1],['landing_path','Landing Path','text',1],['recommended_action','Rekomendasi','textarea',1],['status','Status','select:OPEN|WORKING|DONE|DISMISSED']]},
nexus_campaign_queue:{g:'GROWTH',n:'Campaign Queue',h:'Kampanye yang wajib melewati approval manusia.',f:[['campaign_key','Campaign Key','text',1],['channel','Channel','text',1],['campaign_type','Tipe','text'],['objective','Objective','text'],['status','Status','text'],['policy_status','Policy','text'],['approval_required','Approval Required','bool'],['human_approved','Human Approved','bool'],['title','Judul','text',1],['body','Body','textarea'],['cta_label','CTA','text'],['landing_path','Landing Path','text',1],['utm_source','UTM Source','text',1],['utm_medium','UTM Medium','text',1],['utm_campaign','UTM Campaign','text',1],['utm_content','UTM Content','text'],['target_audience','Target Audience','text'],['scheduled_at','Jadwal','datetime'],['spend_cap','Batas Belanja','number']]},
nexus_operations_tasks:{g:'MANAJEMEN',n:'Operations Tasks',h:'Task yang terhubung booking/customer.',f:[['booking_id','Booking','booking'],['customer_id','Pelanggan','customer'],['task_type','Tipe Task','text',1],['priority','Prioritas','text'],['status','Status','text'],['title','Judul','text',1],['notes','Catatan','textarea'],['due_at','Deadline','datetime'],['assigned_to','PIC UUID','text']]}
};
const R={vehicle:['vehicles','id','name'],customer:['customers','id','full_name'],unit:['vehicle_units','id','unit_code'],booking:['bookings','id','booking_code'],driver:['drivers','id','full_name']};
let db,key='vehicles',data=[],edit=null,rel={},currentUser;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function groups(){const g={};Object.entries(M).forEach(([k,m])=>(g[m.g]??=[]).push([k,m]));$('#menu').innerHTML=Object.entries(g).map(([x,a])=>'<div class="nav-group">'+x+'</div>'+a.map(([k,m])=>'<button class="nav-item" data-key="'+k+'">'+m.n+'</button>').join('')).join('');document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>openModule(b.dataset.key))}
async function openModule(k){key=k;edit=null;const m=M[k];$('#pageTitle').textContent=m.n;$('#moduleTitle').textContent=m.n;$('#moduleHint').textContent=m.h;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.key===k));await load()}
async function load(){state('Memuat…');const m=M[key],r=await db.from(key).select('*').order('created_at',{ascending:false}).limit(500);if(r.error){note(r.error.message,true);data=[]}else{data=r.data||[];note('');await relations(m)}render();form(null);state('Siap')}
async function relations(m){rel={};for(const f of m.f){if(!R[f[2]])continue;const [t,id,n]=R[f[2]],r=await db.from(t).select(id+','+n).order(n).limit(500);if(!r.error)rel[f[2]]=r.data}}
function render(){const q=$('#searchBox').value.toLowerCase(),a=data.filter(x=>!q||Object.values(x).some(v=>String(v??'').toLowerCase().includes(q)));$('#listMeta').textContent=a.length+' dari '+data.length+' record';$('#dataList').innerHTML=a.map(x=>{const f=M[key].f[0][0],g=M[key].f[1]?.[0];return '<div class="row '+(edit?.id===x.id?'active':'')+'" data-id="'+x.id+'"><b>'+esc(x[f]??x.id)+'</b><small>'+esc(g?x[g]??'':x.status??'')+'</small></div>'}).join('')||'<div class="row"><small>Belum ada data.</small></div>';document.querySelectorAll('.row[data-id]').forEach(x=>x.onclick=()=>form(data.find(y=>y.id===x.dataset.id)))}
function input(f,r){const[k,l,t,req]=f,v=r?.[k];let s='<label>'+esc(l);if(t==='bool')s+='<select name="'+k+'"><option value="true" '+(v===true?'selected':'')+'>Ya</option><option value="false" '+(v===false?'selected':'')+'>Tidak</option></select>';else if(t.startsWith('select:'))s+='<select name="'+k+'"><option value="">— pilih —</option>'+t.slice(7).split('|').map(o=>'<option value="'+esc(o)+'" '+(String(v??'')===o?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>';else if(R[t])s+='<select name="'+k+'"><option value="">— pilih —</option>'+(rel[t]||[]).map(o=>'<option value="'+o[R[t][1]]+'" '+(String(v??'')===String(o[R[t][1]])?'selected':'')+'>'+esc(o[R[t][2]])+'</option>').join('')+'</select>';else if(t==='textarea')s+='<textarea name="'+k+'" '+(req?'required':'')+'>'+esc(Array.isArray(v)?v.join(', '):v??'')+'</textarea>';else{s+='<input name="'+k+'" type="'+(t==='array'?'text':t==='number'?'number':t==='datetime'?'datetime-local':t)+'" value="'+esc(t==='array'?(v||[]).join(', '):v??'')+'" '+(req?'required':'')+'>'}return s+'</label>'}
function form(r){edit=r?{...r}:null;$('#formTitle').textContent=r?'Edit Record':'Data Baru';$('#recordForm').innerHTML=M[key].f.map(f=>input(f,r)).join('');$('#deleteBtn').classList.toggle('hidden',!r);render()}
async function save(e){e.preventDefault();const p={},fd=new FormData(e.target);M[key].f.forEach(([k,,t])=>{let v=fd.get(k);if(v==='')v=null;else if(t==='number')v=Number(v);else if(t==='bool')v=v==='true';else if(t==='array')v=v.split(',').map(x=>x.trim()).filter(Boolean);else if(t==='datetime')v=new Date(v).toISOString();p[k]=v});state('Menyimpan…');const r=edit?await db.from(key).update(p).eq('id',edit.id).select().single():await db.from(key).insert(p).select().single();if(r.error){note('Gagal: '+r.error.message,true);state('Error');return}note('Data berhasil disimpan.');edit=r.data;await load();form(r.data);state('Tersimpan')}
async function del(){if(!edit||!confirm('Hapus record ini?'))return;state('Menghapus…');const r=await db.from(key).delete().eq('id',edit.id);if(r.error){note('Gagal: '+r.error.message,true);state('Error');return}edit=null;await load();state('Siap')}
function note(t,e){$('#appNotice').innerHTML=t?'<div class="notice">'+esc(t)+'</div>':''}
function state(t){$('#saveState').textContent=t}
async function login(e){e.preventDefault();const r=await db.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(r.error){$('#loginError').textContent=r.error.message;return}currentUser=r.data.user;show()}
function show(){ $('#loginView').hidden=true;$('#workspace').hidden=false;$('#logoutBtn').hidden=false;$('#userEmail').textContent=currentUser?.email||'';openModule(key)}
async function boot(){db=window.getTransmindSupabaseClient&&window.getTransmindSupabaseClient();if(!db){$('#loginError').textContent='Supabase client tidak tersedia.';return}groups();$('#loginForm').onsubmit=login;$('#logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};$('#newBtn').onclick=()=>form(null);$('#refreshBtn').onclick=load;$('#backBtn').onclick=()=>form(null);$('#resetBtn').onclick=()=>form(edit);$('#deleteBtn').onclick=del;$('#recordForm').onsubmit=save;$('#searchBox').oninput=render;$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');const s=await db.auth.getSession();if(s.data.session){currentUser=s.data.session.user;show()}}
document.addEventListener('DOMContentLoaded',boot);
})();