import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const ORIGIN="https://transmindnusantararentalmobil.co.id";
const cors={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(d:Record<string,unknown>,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors});
const rupiah=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Math.round(n));
function classify(q:string){const s=q.toLowerCase(),tags:string[]=[];const humanRequired=/refund|pengembalian|komplain|keluhan|harga khusus|diskon khusus|ketersediaan pasti|ubah booking|batalkan booking|cancel booking|ganti tanggal|kerusakan|kecelakaan|klaim|kontrak|legal/.test(s);if(/harga|biaya|tarif|sewa|berapa|budget/.test(s))tags.push("harga");if(/booking|pesan|reservasi|rental/.test(s))tags.push("booking");if(/driver|supir|sopir|pengemudi/.test(s))tags.push("driver");if(/lepas\s*kunci/.test(s))tags.push("lepas_kunci");if(/wisata|libur|destinasi|puncak|bandung/.test(s))tags.push("wisata");if(/keluarga|anak|bayi/.test(s))tags.push("keluarga");if(/corporate|kantor|bisnis|dinas/.test(s))tags.push("corporate");if(/wedding|nikah|pernikahan/.test(s))tags.push("wedding");const service=/wedding|nikah|pernikahan/.test(s)?"wedding":/pariwisata|wisata/.test(s)?"pariwisata":/corporate|kantor|bisnis|dinas/.test(s)?"corporate":/lepas\s*kunci/.test(s)?"lepas kunci":/driver|supir|sopir|pengemudi/.test(s)?"dengan driver":null;const vm=["toyota alphard","toyota vellfire","toyota hiace premio","toyota hiace commuter","innova zenix","innova venturer","toyota avanza","toyota veloz","toyota rush","mitsubishi pajero","mitsubishi xpander","honda brio","honda cr-v","honda accord","mercedes-benz e 300","mercedes-benz s 450","bmw","hyundai palisade","isuzu elf","big bus"].find(x=>s.includes(x))||null;const dm=s.match(/(\d+)\s*(hari|day|d)/i),pm=s.match(/(\d+)\s*(orang|org|penumpang|pax)/i);return{tags,intent:tags.includes("harga")?"pricing":tags.includes("booking")?"booking":tags.includes("wisata")?"travel_planning":"rental_consultation",service,vehicle_hint:vm,duration_days:dm?Math.max(1,Number(dm[1])):1,passenger_count:pm?Number(pm[1]):null,human_required:humanRequired};}
async function quote(s:any,c:any,b:any){let v:any=null;if(b.vehicle_id){const r=await s.from("vehicles").select("id,name,category,capacity").eq("id",b.vehicle_id).eq("active",true).maybeSingle();v=r.data;}if(!v&&c.vehicle_hint){const r=await s.from("vehicles").select("id,name,category,capacity").eq("active",true).ilike("name","%"+c.vehicle_hint+"%").limit(1).maybeSingle();v=r.data;}const service=b.service||c.service||"lepas kunci",days=Math.max(1,Number(b.duration_days||c.duration_days||1));if(!v)return{exact:false,message:"Pilih kendaraan agar saya dapat menghitung harga pasti.",service,duration_days:days};const r=await s.from("vehicle_prices").select("daily_price,service,updated_at").eq("vehicle_id",v.id).eq("active",true).ilike("service",service).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(!r.data)return{exact:false,message:"Harga kendaraan tersebut untuk layanan ini belum tersedia di price master aktif.",vehicle:v,service,duration_days:days};const daily=Number(r.data.daily_price),total=daily*days;return{exact:true,vehicle:v,service,duration_days:days,daily_price:daily,total_price:total,formatted_daily_price:rupiah(daily),formatted_total:rupiah(total),basis:"Price master aktif yang digunakan alur booking Transmind",exclusions:service==="dengan driver"||service==="pariwisata"?"BBM, tol, parkir atau biaya khusus tujuan dapat dihitung terpisah.":null};}
function requirements(c:any){return c.tags.includes("lepas_kunci")?"Untuk alur verifikasi identitas Transmind, sistem menyediakan verifikasi dengan data identitas serta dokumen KTP, SIM A, dan selfie. Persyaratan final mengikuti hasil verifikasi/customer care.":"Untuk booking siapkan nama, WhatsApp, kendaraan/kelas, tanggal, area/tujuan, durasi dan kebutuhan khusus. Jika diperlukan verifikasi identitas, sistem menyediakan alur KTP, SIM A dan selfie.";}
function wa(m:string){return"https://wa.me/628816654141?text="+encodeURIComponent(m);}
async function lead(s:any,b:any,c:any,q:any){
 const name=String(b?.lead?.name||"").trim();
 const phone=String(b?.lead?.phone||"").replace(/[^0-9]/g,"");
 const consent=b?.lead?.consent===true;
 if(!name||phone.length<9||!consent)return null;
 const cr=await s.rpc("get_or_create_customer",{p_name:name,p_phone:phone});
 const cid=cr.data;
 if(!cid)return null;
 const now=new Date();
 const stages=[
  {key:"30m",minutes:30,text:"Halo "+name+", saya ingin memastikan kebutuhan rental Anda sudah terjawab. Kalau mau, saya bisa bantu lanjutkan kendaraan, tanggal dan layanan yang tadi dibahas."},
  {key:"1d",minutes:1440,text:"Selamat pagi "+name+". Semoga harinya lancar. Kalau rencana rental Transmind masih dibutuhkan, saya siap bantu cek kembali detail perjalanan Anda."},
  {key:"3d",minutes:4320,text:"Halo "+name+", saya menyapa kembali. Jika rencana perjalanan Anda berubah, tidak masalah—saya bisa bantu menyesuaikan kendaraan, durasi atau layanan sebelum Anda memutuskan booking."},
  {key:"7d",minutes:10080,text:"Halo "+name+", semoga kabarnya baik. Jika kebutuhan perjalanan Anda masih ada, Transmind siap membantu ketika waktunya sudah tepat."}
 ];
 const next=new Date(now.getTime()+30*60000).toISOString();
 const existing=await s.from("customer_care_leads").select("id,customer_id").eq("phone",phone).eq("status","open").order("created_at",{ascending:false}).limit(1).maybeSingle();
 const leadRow={customer_id:cid,session_id:b.session_id,name,phone,consent_status:"granted",source:"website_ai",stage:c.intent==="booking"?"booking_ready":"qualified_lead",intent:c.intent,quote_value:q?.total_price||null,status:"open",human_required:c.human_required,human_reason:c.human_required?"Keputusan membutuhkan admin/otorisasi.":null,last_activity_at:now,next_followup_at:next,followup_stage:"30m",metadata:{quote:q||null,tags:c.tags,source_path:b.path||"/",lead_capture:"explicit_consent"}};
 const lr=existing.data?.id
  ? await s.from("customer_care_leads").update(leadRow).eq("id",existing.data.id).select("id").maybeSingle()
  : await s.from("customer_care_leads").insert(leadRow).select("id").single();
 const leadId=lr.data?.id||existing.data?.id||null;
 if(leadId){
   for(const stage of stages){
     const scheduled=new Date(now.getTime()+stage.minutes*60000).toISOString();
     await s.from("customer_care_followup_queue").upsert({lead_id:leadId,stage:stage.key,scheduled_at:scheduled,channel:"whatsapp",message_body:stage.text,status:"queued",requires_human:false,metadata:{consent_status:"granted",intent:c.intent,quote_value:q?.total_price||null,source:"transmind_ai"}},{onConflict:"lead_id,stage"});
   }
   await s.from("customer_care_learning").insert({lead_id:leadId,session_id:b.session_id,signal_type:"lead_captured",signal_value:{intent:c.intent,tags:c.tags,vehicle:c.vehicle_hint,service:c.service,duration_days:c.duration_days,quote_value:q?.total_price||null,human_required:c.human_required},outcome:"open"});
 }
 await s.from("crm_tasks").insert({customer_id:cid,task_type:"AI_LEAD_FOLLOWUP",priority:q?.total_price?"high":"normal",status:"open",title:"Follow-up calon pelanggan dari Asisten AI",notes:"Lead dari website/Asisten AI; follow-up bertahap 30m, 1d, 3d, 7d. AI wajib menyerahkan keputusan khusus kepada admin.",pipeline_stage:"qualified_lead",next_followup_at:next,quote_value:q?.total_price||null,metadata:{source:"transmind_ai",lead_id:leadId,quote:q||null,tags:c.tags,consent_status:"granted",human_required:c.human_required,followup_sequence:stages.map(x=>x.key),followup_stage:"30m"}});
 const memory=b?.lead?.memory||[];
 if(Array.isArray(memory)) for(const item of memory.slice(0,12)){
  const value=String(item.value||"").trim(); if(!value)continue;
  await s.from("customer_interactions").insert({customer_id:cid,interaction_type:"ai_memory",channel:"website_ai",direction:"inbound",subject:String(item.type||"relationship_note"),content:value,outcome:"captured",metadata:{session_id:b.session_id,consent_status:item.consent===false?"revoked":"granted",source:"ai_customer_care"},occurred_at:item.event_date||now.toISOString()});
  const allowed=["birthday","important_date","preference","family_context","travel_preference","relationship_note"];
  const memoryType=allowed.includes(String(item.type||""))?String(item.type):"relationship_note";
  await s.from("customer_care_memory").insert({customer_id:cid,phone,name,memory_type:memoryType,memory_value:value,event_date:item.event_date||null,source:"ai_customer_care",consent_status:item.consent===false?"revoked":"granted",active:item.consent!==false,metadata:{session_id:b.session_id}});
 }
 for(const stage of stages){
  await s.from("nexus_communications").insert({customer_id:cid,channel:"whatsapp",direction:"outbound",event_type:"AI_LEAD_FOLLOWUP",recipient:phone,message_template:"ai_followup_"+stage.key,message_body:stage.text,provider:"pending_whatsapp_provider",status:"queued",metadata:{scheduled_at:new Date(now.getTime()+stage.minutes*60000).toISOString(),consent_status:"granted",lead_name:name,intent:c.intent,followup_stage:stage.key,delivery_mode:"admin_or_provider_queue"}});
 }
 return{captured:true,lead_id:leadId,next_followup_at:next,followup_stages:stages.map(x=>x.key),whatsapp_link:wa(stages[0].text),delivery_status:"queued_for_admin_or_authorized_provider"};
}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.headers.get("origin")!==ORIGIN)return json({success:false,message:"Origin tidak diizinkan."},403);if(req.method!=="POST")return json({success:false,message:"Gunakan POST."},405);try{const b=await req.json(),m=String(b.message||"").trim(),sid=String(b.session_id||"").trim();if(!m||!sid)return json({success:false,message:"message dan session_id wajib."},400);const s=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!),c=classify(m),now=new Date().toISOString();await s.from("ai_companion_sessions").upsert({session_id:sid,path:String(b.path||"/").slice(0,500),referrer:String(b.referrer||"").slice(0,1000),last_seen_at:now},{onConflict:"session_id"});await s.from("ai_companion_messages").insert({session_id:sid,role:"user",content:m,source:"ai_companion",intent:c.intent,tags:c.tags});const priorPhone=String(b?.lead?.phone||"").replace(/[^0-9]/g,"");
 const priorName=String(b?.lead?.name||"").trim();
 const priorQuery=priorPhone
  ? await s.from("customer_interactions").select("subject,content,occurred_at,customers!inner(full_name,phone)").eq("customers.phone",priorPhone).eq("interaction_type","ai_memory").order("occurred_at",{ascending:false}).limit(8)
  : priorName
   ? await s.from("customer_interactions").select("subject,content,occurred_at,customers!inner(full_name,phone)").ilike("customers.full_name",priorName).eq("interaction_type","ai_memory").order("occurred_at",{ascending:false}).limit(8)
   : {data:[],error:null};
const priorMemory=priorQuery||{data:[],error:null};
const q=(c.intent==="pricing"||c.intent==="booking"||b.quote===true)?await quote(s,c,b):null;
const lostIntent=/tidak jadi|nggak jadi|gak jadi|belum jadi|tidak jadi booking|batalkan rencana|cancel/i.test(m);
const leadPhone=String(b?.lead?.phone||"").replace(/[^0-9]/g,"");
const remembered=(priorMemory?.data||[]).filter((x:any)=>String(x.content||"").trim());
if(lostIntent&&leadPhone&&b?.lead?.consent===true){
 const lost=await s.from("customer_care_leads").update({status:"lost",last_activity_at:now,next_followup_at:null,metadata:{lost_reason:"customer_declined_or_deferred",last_message:m}}).eq("phone",leadPhone).eq("status","open");
 await s.from("customer_care_followup_queue").update({status:"cancelled",outcome:"lead_marked_lost"}).eq("status","queued").in("lead_id",(await s.from("customer_care_leads").select("id").eq("phone",leadPhone).eq("status","lost")).data?.map((x:any)=>x.id)||[]);
}let answer="";if(q?.exact)answer=["Perincian estimasi Transmind:","Kendaraan: "+q.vehicle.name,"Layanan: "+q.service,"Durasi: "+q.duration_days+" hari","Harga harian: "+q.formatted_daily_price,"Subtotal: "+q.formatted_total,q.exclusions||"","Harga dihitung dari price master aktif; konfirmasi akhir mengikuti ketersediaan operasional."].filter(Boolean).join("\n");else if(c.intent==="pricing")answer=(q?.message||"Sebutkan kendaraan, layanan dan durasi agar saya hitungkan.")+"\n\n"+requirements(c);else if(c.human_required)answer="Untuk hal ini saya perlu meneruskannya kepada admin Transmind agar jawabannya tepat dan sesuai kewenangan. Saya akan membantu menyiapkan konteks percakapannya.";else if(c.intent==="booking")answer="Saya siap menyiapkan booking. Kirim kendaraan, tanggal, tujuan/area, jumlah penumpang, durasi, dan pilih lepas kunci atau dengan pengemudi.\n\n"+requirements(c);else if(c.intent==="travel_planning")answer="Saya dapat membantu itinerary, kendaraan dan kebutuhan perjalanan. Berikan asal, tujuan, tanggal, durasi dan jumlah orang.";else answer="Saya siap membantu rental, harga, armada, persyaratan dan booking Transmind. Sebutkan kendaraan atau kebutuhan perjalanan Anda.";const phoneFromMessage=(m.match(/(?:\+?62|0)\s*[0-9\s-]{8,}/)?.[0]||"").replace(/[^0-9]/g,""); const leadPayload=b.lead?{...b.lead,phone:b.lead.phone||phoneFromMessage,consent:b.lead.consent===true}:null; const l=leadPayload?.consent===true?await lead(s,{...b,lead:leadPayload},c,q):null;
if(b.booking_stage==="booking_success"&&l?.captured){
 await s.from("customer_care_leads").update({status:"booked",stage:"booked",last_activity_at:now,next_followup_at:null}).eq("phone",leadPayload.phone).eq("status","open");
 const bookedIds=(await s.from("customer_care_leads").select("id").eq("phone",leadPayload.phone).eq("status","booked")).data?.map((x:any)=>x.id)||[];
 if(bookedIds.length) await s.from("customer_care_followup_queue").update({status:"cancelled",outcome:"booking_completed"}).eq("status","queued").in("lead_id",bookedIds);
 await s.from("customer_care_learning").insert({session_id:b.session_id,signal_type:"booking_converted",signal_value:{phone:leadPayload.phone,intent:c.intent,quote_value:q?.total_price||null},outcome:"booked"});
 await s.from("nexus_communications").insert({customer_id:l?.lead_id||null,channel:"internal",direction:"outbound",event_type:"AI_BOOKING_SUCCESS_CARE",recipient:leadPayload.phone,message_template:"ai_booking_success_care",message_body:"Terima kasih, "+leadPayload.name+". Booking Anda sudah tercatat. Tim Transmind akan melanjutkan detail perjalanan bila diperlukan.",provider:"internal",status:"queued",metadata:{consent_status:"granted",booking_stage:"booking_success"}});
}
if(remembered.length&&!c.human_required){answer="Saya masih menyimpan konteks percakapan Anda sebelumnya, jadi kita tidak perlu mengulang semuanya.\\n\\n"+answer;}
const w=wa(q?.exact?"Halo Transmind Nusantara, saya ingin melanjutkan "+q.vehicle.name+" | "+q.service+" | "+q.duration_days+" hari | estimasi "+q.formatted_total+".":"Halo Transmind Nusantara, saya ingin melanjutkan konsultasi rental dari Asisten AI.");await s.from("ai_companion_messages").insert({session_id:sid,role:"assistant",content:answer,source:"pricing_crm_engine",intent:c.intent,tags:c.tags,metadata:{quote:q,lead:l,human_required:c.human_required,learning_signal:{intent:c.intent,vehicle:c.vehicle_hint,service:c.service,duration_days:c.duration_days,converted:Boolean(l)}}});await s.from("ai_companion_messages").insert({session_id:sid,role:"system",content:"learning_signal",source:"customer_care_learning",intent:c.intent,tags:c.tags,metadata:{human_required:c.human_required,converted:Boolean(l),booking_stage:b.booking_stage||null,lead_captured:Boolean(l),service:c.service,vehicle:c.vehicle_hint,duration_days:c.duration_days}});
if(c.intent!=="rental_consultation")await s.from("ai_companion_demand_signals").insert({session_id:sid,intent:c.intent,tags:c.tags,passenger_count:c.passenger_count,duration_days:c.duration_days,service_type:c.service,vehicle_class:c.vehicle_hint,demand_text:m,source:"ai_companion",metadata:{quote:q,lead:l,phone:leadPayload?.phone||null,lead_name:leadPayload?.name||null,consent_status:leadPayload?.consent===true?"granted":"unknown"}});return json({success:true,answer,intent:c.intent,tags:c.tags,quote:q,requirements:requirements(c),whatsapp_link:w,lead:l});}catch(e){console.error(e);return json({success:false,message:"Asisten AI sedang mengalami gangguan sementara."},500);}});
