'use strict';
(function(){
const client=window.supabase.createClient(window.TRANSMIND_SUPABASE_URL,window.TRANSMIND_SUPABASE_ANON_KEY);
let vehicles=[],units=[],prices=[],availability=[],documents=[],history=[],undoStack=[],currentTab='data';
const $=id=>document.getElementById(id),toast=m=>{const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2500)},esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const dataFor=()=>({data:vehicles,units,pricing:prices,availability,documents,history}[currentTab]||[]);
async function q(t){const r=await client.from(t).select('*').order('created_at',{ascending:false});if(r.error){toast(r.error.message);return[]}return r.data||[]}
async function loadAll(){[vehicles,units,prices,availability,documents,history]=await Promise.all([q('vehicles'),q('vehicle_units'),q('vehicle_prices'),q('vehicle_availability'),q('vehicle_documents'),q('vehicle_change_history')]);render()}
function vname(id){return vehicles.find(v=>v.id===id)?.name||'—'}
function pushUndo(fn,label){undoStack.unshift({fn,label});undoStack=undoStack.slice(0,10);$('undoBtn').disabled=false}
async function undo(){const x=undoStack.shift();if(!x)return;$('undoBtn').disabled=undoStack.length===0;await x.fn();await loadAll();toast('Undo: '+x.label)}
function close(){$('drawer').classList.add('hidden')}
function vehicleSelect(id){return '<select id="f_vehicle" required><option value="">Pilih armada</option>'+vehicles.map(v=>'<option value="'+v.id+'" '+(v.id===id?'selected':'')+'>'+esc(v.name)+'</option>').join('')+'</select>'}
async function saveTable(table,id,payload,label){if(id){const old=dataFor().find(x=>x.id===id);const r=await client.from(table).update(payload).eq('id',id);if(r.error){toast(r.error.message);return false}pushUndo(async()=>{await client.from(table).update(old).eq('id',id)},label+' dibatalkan')}else{const r=await client.from(table).insert(payload).select().single();if(r.error){toast(r.error.message);return false}pushUndo(async()=>{await client.from(table).delete().eq('id',r.data.id)},label+' dibatalkan')}toast(id?'Data diperbarui':'Data ditambahkan');return true}
function openForm(tab,row){let title='',body='',table='',payload=()=>({});
if(tab==='data'){title='Armada';table='vehicles';body='<div class="grid2"><label>Nama*<input id="f_name" required value="'+esc(row?.name||'')+'"></label><label>Slug*<input id="f_slug" required value="'+esc(row?.slug||'')+'"></label><label>Kategori<input id="f_category" value="'+esc(row?.category||'')+'"></label><label>Kapasitas<input id="f_capacity" value="'+esc(row?.capacity||'')+'"></label><label>Total Unit<input id="f_total" type="number" min="0" value="'+(row?.total_units??5)+'"></label><label>Urutan<input id="f_sort" type="number" value="'+(row?.sort_order??0)+'"></label></div><label>Aktif <input id="f_active" type="checkbox" '+(row?.active!==false?'checked':'')+'></label>';payload=()=>({name:$('f_name').value.trim(),slug:$('f_slug').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,''),category:$('f_category').value||null,capacity:$('f_capacity').value||null,total_units:Number($('f_total').value)||0,sort_order:Number($('f_sort').value)||0,active:$('f_active').checked})}
if(tab==='units'){title='Unit Armada';table='vehicle_units';body='<div class="grid2"><label>Armada*'+vehicleSelect(row?.vehicle_id)+'</label><label>Kode Unit*<input id="f_code" required value="'+esc(row?.unit_code||'')+'"></label><label>Nomor Polisi<input id="f_plate" value="'+esc(row?.plate_number||'')+'"></label><label>Status<select id="f_status"><option>AVAILABLE</option><option>RENTED</option><option>MAINTENANCE</option><option>INACTIVE</option></select></label><label>Odometer<input id="f_odo" type="number" value="'+(row?.odometer||0)+'"></label></div><label>Catatan<textarea id="f_notes">'+esc(row?.notes||'')+'</textarea></label>';payload=()=>({vehicle_id:$('f_vehicle').value,unit_code:$('f_code').value.trim(),plate_number:$('f_plate').value||null,status:$('f_status').value,odometer:Number($('f_odo').value)||0,notes:$('f_notes').value||null})}
if(tab==='pricing'){title='Harga Armada';table='vehicle_prices';body='<div class="grid2"><label>Armada*'+vehicleSelect(row?.vehicle_id)+'</label><label>Layanan<input id="f_service" value="'+esc(row?.service_type||'RENTAL')+'"></label><label>Area<input id="f_area" value="'+esc(row?.area||'')+'"></label><label>Durasi (hari)<input id="f_days" type="number" min="1" value="'+(row?.duration_days||1)+'"></label><label>Harga<input id="f_price" type="number" min="0" value="'+(row?.price||0)+'"></label><label>Aktif<select id="f_active"><option value="true">Aktif</option><option value="false">Nonaktif</option></select></label></div>';payload=()=>({vehicle_id:$('f_vehicle').value,service_type:$('f_service').value||'RENTAL',area:$('f_area').value||null,duration_days:Number($('f_days').value)||1,price:Number($('f_price').value)||0,active:$('f_active').value==='true'})}
if(tab==='availability'){title='Ketersediaan';table='vehicle_availability';body='<div class="grid2"><label>Armada*'+vehicleSelect(row?.vehicle_id)+'</label><label>Status<select id="f_status"><option>AVAILABLE</option><option>BLOCKED</option><option>MAINTENANCE</option><option>BOOKED</option></select></label><label>Mulai*<input id="f_from" type="datetime-local" required value="'+(row?.available_from?new Date(row.available_from).toISOString().slice(0,16):'')+'"></label><label>Sampai<input id="f_until" type="datetime-local" value="'+(row?.available_until?new Date(row.available_until).toISOString().slice(0,16):'')+'"></label></div><label>Catatan<textarea id="f_notes">'+esc(row?.notes||'')+'</textarea></label>';payload=()=>({vehicle_id:$('f_vehicle').value,status:$('f_status').value,available_from:new Date($('f_from').value).toISOString(),available_until:$('f_until').value?new Date($('f_until').value).toISOString():null,notes:$('f_notes').value||null})}
if(tab==='documents'){title='Dokumen Armada';table='vehicle_documents';body='<div class="grid2"><label>Armada*'+vehicleSelect(row?.vehicle_id)+'</label><label>Jenis Dokumen*<input id="f_type" required value="'+esc(row?.document_type||'')+'"></label><label>Nomor<input id="f_number" value="'+esc(row?.document_number||'')+'"></label><label>Status<select id="f_status"><option>ACTIVE</option><option>PENDING</option><option>EXPIRED</option></select></label><label>Berlaku<input id="f_issued" type="date" value="'+(row?.issued_at||'')+'"></label><label>Kadaluarsa<input id="f_expires" type="date" value="'+(row?.expires_at||'')+'"></label></div><label>Catatan<textarea id="f_notes">'+esc(row?.notes||'')+'</textarea></label>';payload=()=>({vehicle_id:$('f_vehicle').value,document_type:$('f_type').value.trim(),document_number:$('f_number').value||null,status:$('f_status').value,issued_at:$('f_issued').value||null,expires_at:$('f_expires').value||null,notes:$('f_notes').value||null})}
$('drawerTitle').textContent=(row?'Edit ':'Tambah ')+title;$('drawerBody').innerHTML=body;$('drawer').classList.remove('hidden');$('drawerForm').onsubmit=async e=>{e.preventDefault();const p=payload();if(!p.vehicle_id&&tab!=='data'){toast('Armada wajib dipilih');return}if(tab==='data'&&(!p.name||!p.slug)){toast('Nama dan slug wajib diisi');return}if(await saveTable(table,row?.id,p,title)){$('drawer').classList.add('hidden');await loadAll()}}
}
function render(){const q=($('search').value||'').toLowerCase();const d=dataFor();$('summary').innerHTML=tabSummary();let rows='';if(currentTab==='data'){$('thead').innerHTML='<tr><th>Armada</th><th>Kategori</th><th>Unit</th><th>Status</th><th>Aksi</th></tr>';rows=vehicles.filter(v=>(v.name+' '+v.slug+' '+(v.category||'')).toLowerCase().includes(q)).map(v=>'<tr><td><b>'+esc(v.name)+'</b><small>'+esc(v.slug)+'</small></td><td>'+esc(v.category||'—')+'</td><td>'+v.total_units+'</td><td><span class="badge">'+(v.active?'Aktif':'Nonaktif')+'</span></td><td>'+acts(v)+'</td></tr>').join('')}else if(currentTab==='units'){$('thead').innerHTML='<tr><th>Armada</th><th>Kode</th><th>Plat</th><th>Status</th><th>Odometer</th><th>Aksi</th></tr>';rows=d.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>'<tr><td>'+esc(vname(x.vehicle_id))+'</td><td>'+esc(x.unit_code)+'</td><td>'+esc(x.plate_number||'—')+'</td><td>'+x.status+'</td><td>'+x.odometer+'</td><td>'+acts(x)+'</td></tr>').join('')}else if(currentTab==='pricing'){$('thead').innerHTML='<tr><th>Armada</th><th>Layanan</th><th>Area</th><th>Hari</th><th>Harga</th><th>Aksi</th></tr>';rows=d.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>'<tr><td>'+esc(vname(x.vehicle_id))+'</td><td>'+esc(x.service_type)+'</td><td>'+esc(x.area||'—')+'</td><td>'+x.duration_days+'</td><td>Rp '+Number(x.price).toLocaleString('id-ID')+'</td><td>'+acts(x)+'</td></tr>').join('')}else if(currentTab==='availability'){$('thead').innerHTML='<tr><th>Armada</th><th>Status</th><th>Mulai</th><th>Sampai</th><th>Aksi</th></tr>';rows=d.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>'<tr><td>'+esc(vname(x.vehicle_id))+'</td><td>'+x.status+'</td><td>'+new Date(x.available_from).toLocaleString('id-ID')+'</td><td>'+(x.available_until?new Date(x.available_until).toLocaleString('id-ID'):'—')+'</td><td>'+acts(x)+'</td></tr>').join('')}else if(currentTab==='documents'){$('thead').innerHTML='<tr><th>Armada</th><th>Dokumen</th><th>Nomor</th><th>Status</th><th>Kadaluarsa</th><th>Aksi</th></tr>';rows=d.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>'<tr><td>'+esc(vname(x.vehicle_id))+'</td><td>'+esc(x.document_type)+'</td><td>'+esc(x.document_number||'—')+'</td><td>'+x.status+'</td><td>'+esc(x.expires_at||'—')+'</td><td>'+acts(x)+'</td></tr>').join('')}else{$('thead').innerHTML='<tr><th>Waktu</th><th>Entity</th><th>Aksi</th><th>Actor</th></tr>';rows=d.map(x=>'<tr><td>'+new Date(x.created_at).toLocaleString('id-ID')+'</td><td>'+esc(x.entity_type)+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.actor_user_id||'system')+'</td></tr>').join('')}$('rows').innerHTML=rows||'<tr><td colspan="8" class="loading">Belum ada data.</td></tr>'}
function acts(x){return '<button class="btn ghost" data-edit="'+x.id+'">Edit</button> <button class="btn danger" data-del="'+x.id+'">Hapus</button>'}
function tabSummary(){if(currentTab==='data')return '<div><b>'+vehicles.length+'</b><span>Total Armada</span></div><div><b>'+vehicles.filter(v=>v.active).length+'</b><span>Aktif</span></div><div><b>'+units.length+'</b><span>Unit</span></div><div><b>'+prices.filter(p=>p.active).length+'</b><span>Harga Aktif</span></div>';return '<div><b>'+dataFor().length+'</b><span>Total Record</span></div><div><b>'+undoStack.length+'</b><span>Undo Tersedia</span></div>'}
function setTab(t){currentTab=t;document.querySelectorAll('.submenu a').forEach(a=>a.classList.toggle('active',a.dataset.tab===t));$('pageTitle').textContent={data:'Data Armada',units:'Unit Armada',pricing:'Harga Armada',availability:'Ketersediaan Armada',documents:'Dokumen Armada',history:'Riwayat Armada'}[t];$('newBtn').classList.toggle('hidden',t==='history');render()}
document.querySelectorAll('.submenu a').forEach(a=>a.onclick=e=>{e.preventDefault();setTab(a.dataset.tab)});$('newBtn').onclick=()=>openForm(currentTab);$('search').oninput=render;$('undoBtn').onclick=undo;$('rows').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const x=dataFor().find(r=>r.id===b.dataset.edit||r.id===b.dataset.del);if(!x)return;if(b.dataset.edit)openForm(currentTab,x);else if(confirm('Hapus data ini?')){const table={data:'vehicles',units:'vehicle_units',pricing:'vehicle_prices',availability:'vehicle_availability',documents:'vehicle_documents'}[currentTab],old=x,r=await client.from(table).delete().eq('id',x.id);if(r.error){toast(r.error.message);return}pushUndo(async()=>{await client.from(table).insert(old)},'penghapusan dibatalkan');await loadAll();toast('Data dihapus')}};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=close);
async function init(){const {data:{session}}=await client.auth.getSession();if(!session){$('loginPanel').classList.remove('hidden');return}$('fleetApp').classList.remove('hidden');await loadAll();client.auth.onAuthStateChange((_,s)=>{if(!s)location.reload()})}
$('loginForm').onsubmit=async e=>{e.preventDefault();const r=await client.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(r.error)$('loginError').textContent=r.error.message;else location.reload()};$('logoutBtn').onclick=()=>client.auth.signOut();init();
})();