'use strict';
(()=>{const client=supabase.createClient(window.TRANSMIND_SUPABASE_URL,window.TRANSMIND_SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let role=null,current='home',rows=[],recordIndex=-1,pendingDelete=null;
const modules={
 home:{title:'Workspace',desc:'Pintu masuk pekerjaan dan seluruh modul aplikasi Nexus.',table:null},
 customers:{title:'Customers',desc:'Master customer: data, verifikasi, relasi booking dan riwayat.',table:'customers'},
 bookings:{title:'Bookings',desc:'Aplikasi transaksi booking: input, status, armada, customer dan nilai transaksi.',table:'bookings'},
 crm_tasks:{title:'CRM Tasks',desc:'Work queue follow-up, pipeline, prioritas dan assignment pelanggan.',table:'crm_tasks'},
 interactions:{title:'Interactions',desc:'Log komunikasi customer lintas channel dan hasil interaksi.',table:'customer_interactions'},
 growth_actions:{title:'Growth Actions',desc:'Work queue aksi pertumbuhan yang berasal dari manusia atau engine Nexus.',table:'nexus_growth_actions'},
 opportunities:{title:'Opportunities',desc:'Peluang pertumbuhan dari data nyata yang harus ditindaklanjuti.',table:'nexus_growth_opportunities'},
 campaign_queue:{title:'Campaign Queue',desc:'Manajemen campaign: policy, approval, jadwal dan status publikasi.',table:'nexus_campaign_queue'},
 website_campaigns:{title:'Website Campaigns',desc:'Manajemen konten campaign yang ditampilkan di website publik.',table:'website_campaigns'},
 operations_tasks:{title:'Operations Tasks',desc:'Work queue operasional yang harus dieksekusi dan dipantau.',table:'nexus_operations_tasks'},
 transactions:{title:'Transactions',desc:'Catatan transaksi komersial yang terhubung dengan booking.',table:'transactions'},
 signals:{title:'Intelligence Signals',desc:'Sinyal intelligence untuk keputusan dan tindakan manusia/automation.',table:'nexus_intelligence_signals'},
 analytics:{title:'Production Analytics',desc:'Telemetry produksi read-only. Data pengukuran tidak dapat dimanipulasi dari aplikasi.',table:'website_analytics_events'}
};
const perms={owner:9,admin:9,manager:8,sales:6,operator:6,marketing:6,fleet:6,finance:6,analyst:4,viewer:2};
const fallbackSchemas={
customers:['id','full_name','phone','nik','address','current_address','emergency_name','emergency_phone','emergency_relation','phone_verified','identity_verified','verification_status','risk_level','notes','created_at','updated_at'],
bookings:['id','booking_code','customer_name','customer_phone','vehicle_id','service','start_date','end_date','area','notes','status','created_at','total_price','name','phone','total_days','unit_id','start_datetime','end_datetime','estimated_ready_at','customer_id','verification_status','hold_until','verified_at','verified_by','verification_token','attribution_source','attribution_medium','attribution_campaign','attribution_content','attribution_term','landing_page','referrer_url','agent_id','agent_link_id','partner_id','attribution_code','attributed_at','purpose_primary','purpose_secondary','journey_type','journey_confidence','journey_intelligence'],
crm_tasks:['id','customer_id','booking_id','task_type','priority','status','due_at','assigned_to','title','notes','metadata','completed_at','created_at','updated_at','pipeline_stage','contacted_at','last_contacted_at','next_followup_at','lost_reason','quote_value'],
customer_interactions:['id','customer_id','booking_id','interaction_type','channel','direction','subject','content','outcome','metadata','occurred_at','created_at'],
nexus_growth_actions:['id','customer_id','booking_id','action_type','priority','status','channel','title','message_body','due_at','metadata','created_at','completed_at','updated_at'],
nexus_growth_opportunities:['id','opportunity_key','channel','intent_level','source_type','query_or_theme','landing_path','recommended_action','evidence','status','created_at','updated_at'],
nexus_campaign_queue:['id','campaign_key','channel','campaign_type','objective','status','policy_status','approval_required','human_approved','title','body','cta_label','landing_path','utm_source','utm_medium','utm_campaign','utm_content','utm_term','factual_basis','policy_notes','target_audience','scheduled_at','published_at','spend_cap','created_at','updated_at'],
website_campaigns:['id','campaign_key','campaign_type','title','subtitle','body','cta_label','cta_url','image_url','priority','active','starts_at','ends_at','created_at','updated_at'],
nexus_operations_tasks:['id','booking_id','customer_id','task_type','priority','status','title','notes','due_at','assigned_to','metadata','completed_at','created_at','updated_at'],
transactions:['id','transaction_code','booking_id','customer_id','agent_id','partner_id','vehicle_id','unit_id','gross_amount','transaction_status','currency','source','created_at','confirmed_at','successful_at','cancelled_at','updated_at'],
nexus_intelligence_signals:['id','signal_code','signal_type','severity','entity_type','entity_id','booking_id','title','summary','score','metadata','status','detected_at','resolved_at','created_at','updated_at'],
website_analytics_events:['id','event_type','visitor_session_id','occurred_at','path','title','source','medium','campaign','content','term','referrer_host','metadata','booking_id','booking_code']
};
const rank=()=>perms[role]||0;
function canWrite(m){if(m==='analytics')return false;if(m==='transactions')return ['owner','admin','manager','finance'].includes(role);if(['signals','opportunities'].includes(m))return ['owner','admin','manager','analyst','marketing'].includes(role);if(['campaign_queue','website_campaigns'].includes(m))return ['owner','admin','manager','marketing'].includes(role);if(m==='growth_actions')return ['owner','admin','manager','marketing','sales','operator'].includes(role);return rank()>=6}
function canDelete(){return ['owner','admin','manager'].includes(role)}
function notify(s){const e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2600)}
function setHeader(m){const x=modules[m];$('moduleTitle').textContent=x.title;$('moduleDesc').textContent=x.desc;document.querySelectorAll('#nav a[data-module]').forEach(a=>a.classList.toggle('active',a.dataset.module===m))}
function bindNavigation(){document.querySelectorAll('.nav-section').forEach(b=>b.onclick=()=>{b.classList.toggle('open');b.querySelector('b').textContent=b.classList.contains('open')?'−':'+'});document.querySelectorAll('#nav a[data-module]').forEach(a=>a.onclick=e=>{e.preventDefault();openModule(a.dataset.module)})}
function home(){setHeader('home');$('content').innerHTML='<div class="summary"><div class="metric"><span>AUTHORITY</span><b>'+esc(role||'—')+'</b><span>Role aktif</span></div><div class="metric"><span>DATABASE</span><b>LIVE</b><span>Supabase production</span></div><div class="metric"><span>MODE</span><b>APPLICATION</b><span>CRUD + workflow + RLS</span></div><div class="metric"><span>MODULES</span><b>'+Object.keys(modules).length+'</b><span>Operational modules</span></div></div><div class="notice">Workspace hanya sebagai pintu masuk. Pekerjaan dilakukan melalui modul aplikasi; Insert, View, Update, Delete, navigasi record, Search, Export dan Print mengikuti role serta RLS database.</div><div class="home-grid" style="margin-top:14px">'+Object.entries(modules).filter(([k])=>k!=='home').map(([k,v])=>'<div class="home-card" data-home="'+k+'"><b>'+v.title+'</b><span>'+v.desc+'</span></div>').join('')+'</div>';document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>openModule(x.dataset.home))}
async function schema(table){const r=await client.from(table).select('*').limit(1);if(!r.error&&r.data?.[0])return Object.keys(r.data[0]);return fallbackSchemas[Object.keys(modules).find(k=>modules[k].table===table)]||[]}
function formatValue(v){if(v===null||v===undefined)return '—';if(typeof v==='object')return JSON.stringify(v);const s=String(v);return s.length>80?s.slice(0,77)+'…':s}
function fieldSpec(table,col,value){const readonly=['id','created_at','updated_at','verified_at','completed_at','published_at','attributed_at'].includes(col);let type='text',options=null;
if(['metadata','journey_intelligence','evidence','factual_basis','policy_notes'].includes(col)||col.endsWith('_data'))type='json';
else if(['notes','body','message_body','summary','content','description','recommended_action'].includes(col))type='textarea';
else if(col.endsWith('_at')||col==='due_at'||col==='scheduled_at'||col==='occurred_at')type='datetime-local';
else if(col.endsWith('_date')||col==='start_date'||col==='end_date')type='date';
else if(['active','approval_required','human_approved','phone_verified','identity_verified'].includes(col))type='checkbox';
else if(['price','total_price','quote_value','gross_amount','spend_cap','journey_confidence','score'].includes(col))type='number';
if(table==='bookings'&&col==='status')options=['Menunggu','Dikonfirmasi','Berjalan','Selesai','Dibatalkan'];
if(table==='nexus_campaign_queue'&&col==='status')options=['DRAFT','POLICY_REVIEW','APPROVAL_REQUIRED','APPROVED','SCHEDULED','PUBLISHED','PAUSED','REJECTED'];
if(table==='nexus_campaign_queue'&&col==='policy_status')options=['NOT_REVIEWED','PASS','FAIL','NEEDS_HUMAN_REVIEW'];
if(table==='nexus_growth_actions'&&col==='status')options=['OPEN','IN_PROGRESS','DONE','CANCELLED'];
if(table==='nexus_growth_actions'&&col==='priority')options=['LOW','MEDIUM','HIGH','CRITICAL'];
if(table==='nexus_growth_opportunities'&&col==='intent_level')options=['HIGH','MEDIUM','LOW'];
if(table==='nexus_growth_opportunities'&&col==='status')options=['OPEN','WORKING','DONE','DISMISSED'];
if(table==='nexus_intelligence_signals'&&col==='status')options=['OPEN','ACKNOWLEDGED','RESOLVED'];
if(table==='nexus_intelligence_signals'&&col==='severity')options=['LOW','MEDIUM','HIGH','CRITICAL'];
if(['crm_tasks','nexus_operations_tasks'].includes(table)&&col==='status')options=['OPEN','IN_PROGRESS','DONE','CANCELLED'];
if(table==='transactions'&&col==='transaction_status')options=['PENDING','CONFIRMED','SUCCESS','CANCELLED'];
return{readonly,type,options,value}}
function inputHTML(table,col,value){const f=fieldSpec(table,col,value),label=col.replaceAll('_',' ');if(f.type==='checkbox')return '<input data-field="'+col+'" type="checkbox" '+(value?'checked':'')+' '+(f.readonly?'disabled':'')+'>';if(f.options)return '<select data-field="'+col+'" '+(f.readonly?'disabled':'')+'><option value="">—</option>'+f.options.map(o=>'<option value="'+esc(o)+'" '+(String(value??'')===o?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>';if(f.type==='textarea')return '<textarea data-field="'+col+'" '+(f.readonly?'readonly':'')+'>'+esc(value??'')+'</textarea>';if(f.type==='json')return '<textarea data-field="'+col+'" '+(f.readonly?'readonly':'')+'>'+esc(value?JSON.stringify(value,null,2):'{}')+'</textarea>';let val=value??'';if(f.type==='datetime-local'&&val){const d=new Date(val);if(!Number.isNaN(d.getTime()))val=d.toISOString().slice(0,16)}return '<input data-field="'+col+'" type="'+f.type+'" value="'+esc(val)+'" '+(f.readonly?'readonly class="readonly"':'')+'>'}
async function openModule(m){current=m;setHeader(m);if(m==='analytics')return analytics();const table=modules[m].table;if(!table)return home();$('content').innerHTML='<div class="empty">Memuat aplikasi '+esc(modules[m].title)+'…</div>';const r=await client.from(table).select('*').order('created_at',{ascending:false}).limit(500);if(r.error){$('content').innerHTML='<div class="notice error">'+esc(r.error.message)+'</div>';return}rows=r.data||[];renderTable()}
function renderTable(){const writable=canWrite(current),m=modules[current],cols=rows.length?Object.keys(rows[0]).filter(c=>!['id','updated_at','created_at'].includes(c)).slice(0,9):fallbackSchemas[m.table].filter(c=>!['id','updated_at','created_at'].includes(c)).slice(0,9);$('content').innerHTML='<div class="module-head"><div><b>'+rows.length+' record</b><div class="muted">Production data • authority: '+esc(role)+'</div></div><div class="module-actions">'+(writable?'<button class="btn primary" id="insertBtn">＋ Insert</button>':'')+'<button class="btn ghost" id="exportBtn">Export CSV</button><button class="btn ghost" id="printBtn">Print</button></div></div><div class="toolbar"><div class="search">⌕ <input id="filter" placeholder="Search record…"></div></div><div class="table-card"><table class="table"><thead><tr>'+cols.map(c=>'<th>'+c.replaceAll('_',' ')+'</th>').join('')+'<th>Aksi</th></tr></thead><tbody id="tbody"></tbody></table></div>';const draw=()=>{const q=($('filter').value||'').toLowerCase();const visible=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));$('tbody').innerHTML=visible.length?visible.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(formatValue(r[c]))+'</td>').join('')+'<td><div class="row-actions"><button class="btn ghost" data-view="'+r.id+'">View</button>'+(writable?'<button class="btn ghost" data-edit="'+r.id+'">Update</button>':'')+(canDelete()&&writable?'<button class="btn danger" data-del="'+r.id+'">Delete</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="'+(cols.length+1)+'" class="empty">Belum ada record.</td></tr>';attachRows()};$('filter').oninput=draw;draw();if(writable)$('insertBtn').onclick=()=>openRecord(null);$('exportBtn').onclick=exportCSV;$('printBtn').onclick=()=>window.print()}
function attachRows(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openRecord(b.dataset.view));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openRecord(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>requestDelete(b.dataset.del))}
async function openRecord(id){const table=modules[current].table,row=id?rows.find(x=>x.id===id):null;recordIndex=row?rows.findIndex(x=>x.id===id):rows.length;const cols=await schema(table);$('drawerTitle').textContent=(row?'Update ':'Insert ')+modules[current].title;$('recordNav').innerHTML='<button type="button" class="btn ghost" id="first">First</button><button type="button" class="btn ghost" id="prev">‹ Prev</button><span class="position">'+(row?(recordIndex+1)+' / '+rows.length:'New record')+'</span><button type="button" class="btn ghost" id="next">Next ›</button><button type="button" class="btn ghost" id="last">Last</button>';$('formBody').innerHTML='<div class="field-grid">'+cols.map(c=>'<div class="field '+(['notes','body','message_body','summary','content','metadata','journey_intelligence','evidence','factual_basis','policy_notes'].includes(c)?'full':'')+'"><label>'+c.replaceAll('_',' ')+'</label>'+inputHTML(table,c,row?.[c])+'</div>').join('')+'</div>';$('drawer').classList.remove('hidden');const editable=canWrite(current);$('saveBtn').style.display=editable?'block':'none';if(!editable)$('formBody').querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);$('recordForm').onsubmit=e=>saveRecord(e,row,cols);$('first').onclick=()=>navigate(0);$('prev').onclick=()=>navigate(Math.max(0,recordIndex-1));$('next').onclick=()=>navigate(Math.min(rows.length-1,recordIndex+1));$('last').onclick=()=>navigate(Math.max(0,rows.length-1))}
function navigate(i){if(!rows[i])return;recordIndex=i;openRecord(rows[i].id)}
async function saveRecord(e,row,cols){e.preventDefault();const payload={};for(const c of cols){if(['id','created_at','updated_at'].includes(c))continue;const el=document.querySelector('[data-field="'+c+'"]');if(!el||el.disabled)continue;let v=el.type==='checkbox'?el.checked:el.value;if(v==='')v=null;if(el.tagName==='TEXTAREA'&&['metadata','journey_intelligence','evidence','factual_basis','policy_notes'].includes(c)){try{v=v?JSON.parse(v):{} }catch{notify(c+' harus berupa JSON valid');return}}payload[c]=v}const table=modules[current].table,r=row?await client.from(table).update(payload).eq('id',row.id):await client.from(table).insert(payload);if(r.error){notify(r.error.message);return}notify(row?'Record diperbarui':'Record ditambahkan');$('drawer').classList.add('hidden');await openModule(current)}
function requestDelete(id){if(!canDelete())return;pendingDelete=id;$('confirmText').textContent='Record akan dihapus dari '+modules[current].title+'. Tindakan ini mengikuti RLS dan audit database.';$('confirmModal').classList.remove('hidden')}
async function executeDelete(){if(!pendingDelete)return;const id=pendingDelete;pendingDelete=null;$('confirmModal').classList.add('hidden');const r=await client.from(modules[current].table).delete().eq('id',id);if(r.error){notify(r.error.message);return}notify('Record dihapus');await openModule(current)}
function exportCSV(){if(!rows.length)return;const cols=Object.keys(rows[0]),csv=[cols.join(','),...rows.map(r=>cols.map(c=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=current+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click()}
async function analytics(){setHeader('analytics');const r=await client.from('website_analytics_events').select('*').order('occurred_at',{ascending:false}).limit(300);if(r.error){$('content').innerHTML='<div class="notice error">'+esc(r.error.message)+'</div>';return}rows=r.data||[];renderTable()}
async function openAuth(){const s=await client.auth.getSession();if(s.data.session)return true;$('authModal').classList.remove('hidden');return new Promise(resolve=>{$('authForm').onsubmit=async e=>{e.preventDefault();$('authError').textContent='';const r=await client.auth.signInWithPassword({email:$('authEmail').value.trim(),password:$('authPassword').value});if(r.error){$('authError').textContent=r.error.message;return}$('authModal').classList.add('hidden');resolve(true)}})}
async function init(){bindNavigation();$('cancelDelete').onclick=()=>{$('confirmModal').classList.add('hidden');pendingDelete=null};$('confirmDelete').onclick=executeDelete;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('.drawer-wrap')?.classList.add('hidden'));$('refreshBtn').onclick=()=>current==='home'?home():openModule(current);$('logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload()};if(!(await openAuth()))return;const s=await client.auth.getSession(),uid=s.data.session.user.id,p=await client.from('user_profiles').select('role,full_name').eq('id',uid).maybeSingle();role=p.data?.role||s.data.session.user.app_metadata?.role||'viewer';$('roleBadge').textContent=(p.data?.full_name||s.data.session.user.email||'User')+' · '+role;$('dbStatus').textContent='Production DB · authenticated';home()}
init()})();