'use strict';
(()=>{const client=supabase.createClient(window.TRANSMIND_SUPABASE_URL,window.TRANSMIND_SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let role=null,current=null,rows=[],recordIndex=-1,loading=false;
const modules={
 home:{title:'Home',desc:'Command Center dan pintu masuk seluruh aplikasi Nexus.',table:null},
 customers:{title:'Customers',desc:'Master customer: input, koreksi, verifikasi, riwayat dan relasi booking.',table:'customers'},
 bookings:{title:'Bookings',desc:'Aplikasi transaksi booking dengan status, armada, customer dan nilai transaksi.',table:'bookings'},
 crm_tasks:{title:'CRM Tasks',desc:'Pekerjaan follow-up dan pipeline pelanggan.',table:'crm_tasks'},
 interactions:{title:'Interactions',desc:'Catatan komunikasi customer lintas channel.',table:'customer_interactions'},
 growth_actions:{title:'Growth Actions',desc:'Aksi pertumbuhan yang dibuat manusia maupun engine Nexus.',table:'nexus_growth_actions'},
 opportunities:{title:'Opportunities',desc:'Peluang pertumbuhan yang ditemukan dari data nyata.',table:'nexus_growth_opportunities'},
 campaign_queue:{title:'Campaign Queue',desc:'Antrian campaign dengan policy, approval dan jadwal.',table:'nexus_campaign_queue'},
 website_campaigns:{title:'Website Campaigns',desc:'Konten campaign yang tampil pada website publik.',table:'website_campaigns'},
 operations_tasks:{title:'Operations Tasks',desc:'Tugas operasional yang harus dieksekusi dan dipantau.',table:'nexus_operations_tasks'},
 transactions:{title:'Transactions',desc:'Transaksi keuangan/komersial yang terkait booking.',table:'transactions'},
 signals:{title:'Intelligence Signals',desc:'Sinyal intelligence untuk ditindaklanjuti manusia atau automation.',table:'nexus_intelligence_signals'},
 analytics:{title:'Analytics',desc:'Telemetry produksi. Modul ini read-only agar data pengukuran tidak dimanipulasi.',table:'website_analytics_events'}
};
const perms={owner:9,admin:9,manager:8,sales:6,operator:6,marketing:6,fleet:6,finance:6,analyst:4,viewer:2};
const rank=()=>perms[role]||0;
function canWrite(m){if(m==='analytics')return false;if(m==='transactions')return ['owner','admin','manager','finance'].includes(role);if(['signals','opportunities'].includes(m))return ['owner','admin','manager','analyst','marketing'].includes(role);if(['campaign_queue','website_campaigns'].includes(m))return ['owner','admin','manager','marketing'].includes(role);if(['growth_actions'].includes(m))return ['owner','admin','manager','marketing','sales','operator'].includes(role);return rank()>=6}
function canDelete(){return ['owner','admin','manager'].includes(role)}
function notify(s){const e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2600)}
function setHeader(m){const x=modules[m];$('moduleTitle').textContent=x.title;$('moduleDesc').textContent=x.desc;document.querySelectorAll('#nav a[data-module]').forEach(a=>a.classList.toggle('active',a.dataset.module===m))}
function home(){setHeader('home');$('content').innerHTML='<div class="summary"><div class="metric"><span>ROLE</span><b>'+esc(role||'—')+'</b><span>Otoritas aktif</span></div><div class="metric"><span>DATABASE</span><b>LIVE</b><span>Supabase production</span></div><div class="metric"><span>MODE</span><b>APPLICATION</b><span>CRUD + audit + authority</span></div><div class="metric"><span>MODULE</span><b>'+Object.keys(modules).length+'</b><span>Modul operasional</span></div></div><div class="notice">Dashboard hanya ringkasan. Seluruh pekerjaan dilakukan melalui aplikasi di bawah. Hak Insert / Update / Delete mengikuti role dan RLS database.</div><div class="home-grid" style="margin-top:14px">'+Object.entries(modules).filter(([k])=>k!=='home').map(([k,v])=>'<div class="home-card" data-home="'+k+'"><b>'+v.title+'</b><span>'+v.desc+'</span></div>').join('')+'</div>';document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>openModule(x.dataset.home))}
async function schema(table){const r=await client.from(table).select('*').limit(1);if(r.error){notify(r.error.message);return []}return r.data?.[0]?Object.keys(r.data[0]):[]}
function formatValue(v){if(v===null||v===undefined)return '—';if(typeof v==='object')return JSON.stringify(v);const s=String(v);return s.length>80?s.slice(0,77)+'…':s}
function fieldSpec(table,col,value){const readonly=['id','created_at','updated_at','verified_at','completed_at','published_at','attributed_at'].includes(col);let type='text', options=null;
if(col.includes('metadata')||col.includes('intelligence')||col==='factual_basis'||col==='policy_notes'||col.endsWith('_data'))type='json';
else if(col.includes('notes')||col==='body'||col==='message_body'||col==='summary'||col==='content'||col==='description')type='textarea';
else if(col.includes('_at')||col==='due_at'||col==='scheduled_at'||col==='occurred_at')type='datetime-local';
else if(col.endsWith('_date')||col==='start_date'||col==='end_date')type='date';
else if(['active','approval_required','human_approved','phone_verified','identity_verified'].includes(col))type='checkbox';
else if(['price','total_price','quote_value','gross_amount','spend_cap','journey_confidence','score'].includes(col))type='number';
else if(['status','priority','channel','policy_status','verification_status','risk_level','transaction_status','service','direction','interaction_type','task_type','pipeline_stage','signal_type','severity','entity_type','source'].includes(col))type='text';
if(['status'].includes(col)&&table==='bookings')options=['Menunggu','Dikonfirmasi','Berjalan','Selesai','Dibatalkan'];
if(table==='nexus_campaign_queue'&&col==='status')options=['DRAFT','POLICY_REVIEW','APPROVAL_REQUIRED','APPROVED','SCHEDULED','PUBLISHED','PAUSED','REJECTED'];
if(table==='nexus_campaign_queue'&&col==='policy_status')options=['NOT_REVIEWED','PASS','FAIL','NEEDS_HUMAN_REVIEW'];
if(table==='nexus_growth_actions'&&col==='status')options=['OPEN','IN_PROGRESS','DONE','CANCELLED'];
if(table==='nexus_growth_actions'&&col==='priority')options=['LOW','MEDIUM','HIGH','CRITICAL'];
if(table==='nexus_growth_opportunities'&&col==='intent_level')options=['HIGH','MEDIUM','LOW'];
if(table==='nexus_growth_opportunities'&&col==='status')options=['OPEN','WORKING','DONE','DISMISSED'];
if(table==='nexus_intelligence_signals'&&col==='status')options=['OPEN','ACKNOWLEDGED','RESOLVED'];
if(table==='nexus_intelligence_signals'&&col==='severity')options=['LOW','MEDIUM','HIGH','CRITICAL'];
if(table==='crm_tasks'&&col==='status')options=['OPEN','IN_PROGRESS','DONE','CANCELLED'];
if(table==='transactions'&&col==='transaction_status')options=['PENDING','CONFIRMED','SUCCESS','CANCELLED'];
return {readonly,type,options,value}}
function inputHTML(table,col,value){const f=fieldSpec(table,col,value),label=col.replaceAll('_',' ');if(f.type==='checkbox')return '<input data-field="'+col+'" type="checkbox" '+(value?'checked':'')+' '+(f.readonly?'disabled':'')+'>';if(f.options)return '<select data-field="'+col+'" '+(f.readonly?'disabled':'')+'><option value="">—</option>'+f.options.map(o=>'<option value="'+esc(o)+'" '+(String(value??'')===o?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>';if(f.type==='textarea')return '<textarea data-field="'+col+'" '+(f.readonly?'readonly':'')+'>'+esc(value??'')+'</textarea>';if(f.type==='json')return '<textarea data-field="'+col+'" '+(f.readonly?'readonly':'')+'>'+esc(value?JSON.stringify(value,null,2):'{}')+'</textarea>';let val=value??'';if(f.type==='datetime-local'&&val)val=new Date(val).toISOString().slice(0,16);return '<input data-field="'+col+'" type="'+f.type+'" value="'+esc(val)+'" '+(f.readonly?'readonly class="readonly"':'')+'>'}
async function schema(table){const r=await client.from(table).select('*').limit(1);if(r.error){notify(r.error.message);return []}return r.data?.[0]?Object.keys(r.data[0]):[]}
async function openModule(m){current=m;setHeader(m);if(m==='analytics'){return analytics()}const table=modules[m].table;if(!table)return home();loading=true;$('content').innerHTML='<div class="empty">Memuat aplikasi…</div>';const r=await client.from(table).select('*').order('created_at',{ascending:false}).limit(500);loading=false;if(r.error){$('content').innerHTML='<div class="notice error">'+esc(r.error.message)+'</div>';return}rows=r.data||[];renderTable()}
function renderTable(){const m=modules[current], writable=canWrite(current), searchable=['customer_name','full_name','phone','booking_code','title','name','campaign_key','opportunity_key'];$('content').innerHTML='<div class="module-head"><div><b>'+rows.length+' record</b><div class="muted">Data produksi • hak akses: '+esc(role)+'</div></div><div class="module-actions">'+(writable?'<button class="btn primary" id="insertBtn">＋ Insert</button>':'')+'<button class="btn ghost" id="exportBtn">Export CSV</button><button class="btn ghost" id="printBtn">Print</button></div></div><div class="toolbar"><div class="search">⌕ <input id="filter" placeholder="Search record…"></div></div><div class="table-card"><table class="table"><thead id="thead"></thead><tbody id="tbody"></tbody></table></div>';const cols=rows.length?Object.keys(rows[0]).filter(c=>!['id','updated_at','created_at'].includes(c)).slice(0,8):[];$('thead').innerHTML='<tr>'+cols.map(c=>'<th>'+c.replaceAll('_',' ')+'</th>').join('')+'<th>Aksi</th></tr>';const draw=()=>{const q=($('filter').value||'').toLowerCase();const visible=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));$('tbody').innerHTML=visible.length?visible.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(formatValue(r[c]))+'</td>').join('')+'<td><div class="row-actions"><button class="btn ghost" data-view="'+r.id+'">View</button>'+(writable?'<button class="btn ghost" data-edit="'+r.id+'">Update</button>':'')+(canDelete()&&writable?'<button class="btn danger" data-del="'+r.id+'">Delete</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="'+(cols.length+1)+'" class="empty">Belum ada record.</td></tr>';attachRows()};$('filter').oninput=draw;draw();if(writable)$('insertBtn').onclick=()=>openRecord(null);$('exportBtn').onclick=()=>exportCSV();$('printBtn').onclick=()=>window.print()}
function attachRows(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openRecord(b.dataset.view));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openRecord(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeRecord(b.dataset.del))}
async function openRecord(id){const table=modules[current].table;let row=id?rows.find(x=>x.id===id):null;recordIndex=row?rows.findIndex(x=>x.id===id):rows.length;const cols=await schema(table);$('drawerTitle').textContent=(row?'Update ':'Insert ')+modules[current].title;$('recordNav').innerHTML='<button type="button" class="btn ghost" id="first">First</button><button type="button" class="btn ghost" id="prev">‹ Prev</button><span class="position">'+(row?(recordIndex+1)+' / '+rows.length:'New record')+'</span><button type="button" class="btn ghost" id="next">Next ›</button><button type="button" class="btn ghost" id="last">Last</button>';const editable=canWrite(current);$('formBody').innerHTML='<div class="field-grid">'+cols.map(c=>'<div class="field '+(['notes','body','message_body','summary','content','metadata','factual_basis','policy_notes'].includes(c)?'full':'')+'"><label>'+c.replaceAll('_',' ')+'</label>'+inputHTML(table,c,row?.[c])+'</div>').join('')+'</div>';$('drawer').classList.remove('hidden');$('saveBtn').style.display=editable?'block':'none';if(!editable)$('formBody').querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);$('recordForm').onsubmit=e=>saveRecord(e,row,cols);$('first').onclick=()=>navigate(0);$('prev').onclick=()=>navigate(Math.max(0,recordIndex-1));$('next').onclick=()=>navigate(Math.min(rows.length-1,recordIndex+1));$('last').onclick=()=>navigate(rows.length-1)}
function navigate(i){if(!rows[i])return;recordIndex=i;openRecord(rows[i].id)}
async function saveRecord(e,row,cols){e.preventDefault();const table=modules[current].table,payload={};cols.forEach(c=>{if(['id','created_at','updated_at'].includes(c))return;const el=document.querySelector('[data-field="'+c+'"]');if(!el||el.disabled)return;let v=el.type==='checkbox'?el.checked:el.value;if(v==='')v=null;if(el.tagName==='TEXTAREA'&&['metadata','factual_basis','policy_notes'].includes(c)){try{v=v?JSON.parse(v):{} }catch{notify(c+' harus berupa JSON valid');return}}payload[c]=v});const r=row?await client.from(table).update(payload).eq('id',row.id):await client.from(table).insert(payload);if(r.error){notify(r.error.message);return}notify(row?'Record diperbarui':'Record ditambahkan');$('drawer').classList.add('hidden');await openModule(current)}
async function removeRecord(id){if(!canDelete()||!confirm('Hapus record ini? Tindakan ini akan tercatat pada audit/RLS.'))return;const r=await client.from(modules[current].table).delete().eq('id',id);if(r.error){notify(r.error.message);return}notify('Record dihapus');await openModule(current)}
function exportCSV(){const table=modules[current].table;if(!rows.length)return;const cols=Object.keys(rows[0]);const csv=[cols.join(','),...rows.map(r=>cols.map(c=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=current+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click()}
async function analytics(){setHeader('analytics');const r=await client.from('website_analytics_events').select('*').order('occurred_at',{ascending:false}).limit(300);if(r.error){$('content').innerHTML='<div class="notice error">'+esc(r.error.message)+'</div>';return}rows=r.data||[];renderTable()}
async function openAuth(){const s=await client.auth.getSession();if(!s.data.session){const email=prompt('Email Nexus');const password=prompt('Password Nexus');if(!email||!password)return false;const r=await client.auth.signInWithPassword({email,password});if(r.error){alert(r.error.message);return false}}return true}
async function init(){if(!(await openAuth()))return;const s=await client.auth.getSession();const uid=s.data.session.user.id;const p=await client.from('user_profiles').select('role,full_name').eq('id',uid).maybeSingle();role=p.data?.role||s.data.session.user.app_metadata?.role||'viewer';$('roleBadge').textContent=(p.data?.full_name||s.data.session.user.email||'User')+' · '+role;$('dbStatus').textContent='Production DB · authenticated';document.querySelectorAll('#nav a[data-module]').forEach(a=>a.onclick=e=>{e.preventDefault();openModule(a.dataset.module)});$('refreshBtn').onclick=()=>current==='home'?home():openModule(current);$('logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload()};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('drawer').classList.add('hidden'));home()}
init()})()